import { Accessibility, Heart, Briefcase, Scale, ExternalLink, AlertCircle } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import Layout from '@/components/layout/Layout';
import { usePageMeta } from '@/hooks/usePageMeta';

interface BenefitCard {
  label: string;
    desc: string;
      link: string;
        linkLabel: string;
          extra?: { label: string; url: string };
            badge: string;
            }

            const federalBenefits: BenefitCard[] = [
              {
                  label: "Supplemental Security Income (SSI)",
                      desc: "Monthly cash payments for people 65+, blind, or disabled with limited income and resources. Administered by the Social Security Administration.",
                          link: "https://www.ssa.gov/ssi",
                              linkLabel: "Learn About SSI",
                                  extra: { label: "Apply Online", url: "https://www.ssa.gov/applyfordisability/" },
                                      badge: "SSA"
                                        },
                                          {
                                              label: "Social Security Disability Insurance (SSDI)",
                                                  desc: "Benefits for people with disabilities who have worked and paid Social Security taxes. Includes Medicare eligibility after 24 months.",
                                                      link: "https://www.ssa.gov/disability",
                                                          linkLabel: "Learn About SSDI",
                                                              extra: { label: "Apply Online", url: "https://www.ssa.gov/applyfordisability/" },
                                                                  badge: "SSA"
                                                                    },
                                                                      {
                                                                          label: "Medicare for People with Disabilities",
                                                                              desc: "Medicare coverage begins after 24 months of SSDI. Low-income beneficiaries may qualify for Extra Help with drug costs.",
                                                                                  link: "https://www.medicare.gov/basics/get-started-with-medicare/medicare-basics/who-can-get-medicare",
                                                                                      linkLabel: "Medicare Basics",
                                                                                          badge: "CMS"
                                                                                            },
                                                                                              {
                                                                                                  label: "Medicaid for People with Disabilities (Michigan)",
                                                                                                      desc: "Michigan Medicaid covers adults with disabilities including long-term services. MI Choice Waiver provides home and community-based care.",
                                                                                                          link: "https://www.michigan.gov/mdhhs/assistance-programs/medicaid",
                                                                                                              linkLabel: "Michigan Medicaid",
                                                                                                                  extra: { label: "MI Choice Waiver", url: "https://www.michigan.gov/mdhhs/keep-mi-healthy/moms-kids-family/seniors/mi-choice-waiver-program" },
                                                                                                                      badge: "MDHHS"
                                                                                                                        }
                                                                                                                        ];

                                                                                                                        const michiganPrograms: BenefitCard[] = [
                                                                                                                          {
                                                                                                                              label: "Michigan Rehabilitation Services (MRS)",
                                                                                                                                  desc: "Vocational rehabilitation and employment support for people with disabilities, provided by MDHHS and LEO.",
                                                                                                                                      link: "https://www.michigan.gov/leo/bureaus-agencies/wd/mrs",
                                                                                                                                          linkLabel: "Michigan Rehab Services",
                                                                                                                                              badge: "MDHHS / LEO"
                                                                                                                                                },
                                                                                                                                                  {
                                                                                                                                                      label: "Centers for Independent Living",
                                                                                                                                                          desc: "Michigan's CILs provide peer support, skills training, advocacy, and transition services to help people with disabilities live independently.",
                                                                                                                                                              link: "https://www.michigan.gov/mdhhs/keep-mi-healthy/independent-living",
                                                                                                                                                                  linkLabel: "Find a CIL",
                                                                                                                                                                      badge: "MDHHS"
                                                                                                                                                                        },
                                                                                                                                                                          {
                                                                                                                                                                              label: "Michigan Protection & Advocacy Service (MPAS)",
                                                                                                                                                                                  desc: "Free legal advocacy and rights protection for people with disabilities, including education rights, Medicaid appeals, and discrimination complaints.",
                                                                                                                                                                                      link: "https://www.mpas.org",
                                                                                                                                                                                          linkLabel: "MPAS Services",
                                                                                                                                                                                              badge: "MPAS"
                                                                                                                                                                                                },
                                                                                                                                                                                                  {
                                                                                                                                                                                                      label: "ADA Accessibility Complaints",
                                                                                                                                                                                                          desc: "File a complaint about ADA violations in employment, public accommodation, or state services.",
                                                                                                                                                                                                              link: "https://www.ada.gov/filing-a-complaint/",
                                                                                                                                                                                                                  linkLabel: "ADA.gov Complaints",
                                                                                                                                                                                                                      extra: { label: "Michigan MDCR", url: "https://www.michigan.gov/mdcr" },
                                                                                                                                                                                                                          badge: "ADA.gov · MDCR"
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                            ];

                                                                                                                                                                                                                            const legalHelp: BenefitCard[] = [
                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                  label: "Michigan Legal Help – Disability",
                                                                                                                                                                                                                                      desc: "Plain-language guides on applying for SSI/SSDI, appealing denials, and understanding your rights when disabled in Michigan.",
                                                                                                                                                                                                                                          link: "https://michiganlegalhelp.org/topics/benefits-public-assistance",
                                                                                                                                                                                                                                              linkLabel: "Get Legal Help",
                                                                                                                                                                                                                                                  badge: "Michigan Legal Help"
                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                          label: "Disability Rights Advocates",
                                                                                                                                                                                                                                                              desc: "Michigan-specific resources and referrals for disability rights complaints, accessible housing, and employment discrimination.",
                                                                                                                                                                                                                                                                  link: "https://www.mpas.org/legal-resources/",
                                                                                                                                                                                                                                                                      linkLabel: "MPAS Legal Resources",
                                                                                                                                                                                                                                                                          badge: "MPAS"
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                            ];

                                                                                                                                                                                                                                                                            function BenefitCardComponent({ card }: { card: BenefitCard }) {
                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                  <Card>
                                                                                                                                                                                                                                                                                        <CardHeader>
                                                                                                                                                                                                                                                                                                <CardTitle className="text-lg">{card.label}</CardTitle>
                                                                                                                                                                                                                                                                                                        <CardDescription className="text-sm leading-relaxed">{card.desc}</CardDescription>
                                                                                                                                                                                                                                                                                                              </CardHeader>
                                                                                                                                                                                                                                                                                                                    <CardContent className="space-y-2">
                                                                                                                                                                                                                                                                                                                            <Button asChild className="w-full bg-michigan-blue hover:bg-michigan-blue/90" size="sm">
                                                                                                                                                                                                                                                                                                                                      <a href={card.link} target="_blank" rel="noopener noreferrer">
                                                                                                                                                                                                                                                                                                                                                  {card.linkLabel} <ExternalLink className="h-3 w-3 ml-2" />
                                                                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                                                                                    </Button>
                                                                                                                                                                                                                                                                                                                                                                            {card.extra && (
                                                                                                                                                                                                                                                                                                                                                                                      <Button asChild variant="outline" size="sm" className="w-full">
                                                                                                                                                                                                                                                                                                                                                                                                  <a href={card.extra.url} target="_blank" rel="noopener noreferrer">
                                                                                                                                                                                                                                                                                                                                                                                                                {card.extra.label} <ExternalLink className="h-3 w-3 ml-2" />
                                                                                                                                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                      </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Badge variant="secondary" className="w-full justify-center text-xs">{card.badge}</Badge>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default function DisabilityAccess() {
  usePageMeta({
    title: "Disability & Accessibility",
    description: "Federal and Michigan disability benefits, services, and legal aid resources",
    path: "/disability-access",
  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Layout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="min-h-screen bg-background">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Header */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="border-b bg-muted/30">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="container max-w-4xl py-12 space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Accessibility className="h-10 w-10 text-michigan-blue" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h1 className="text-4xl font-bold">Disability & Accessibility</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-lg text-muted-foreground max-w-2xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Federal and Michigan disability benefits, vocational rehabilitation, legal rights, and independent living resources.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="container max-w-4xl py-12 space-y-12">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Federal Benefits */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <section className="space-y-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2 className="text-2xl font-bold flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Heart className="h-6 w-6" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Federal Disability Benefits
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-muted-foreground text-sm">SSA, CMS, and Medicaid programs for people with disabilities</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="grid gap-4 md:grid-cols-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {federalBenefits.map((card) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <BenefitCardComponent key={card.label} card={card} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Separator />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Michigan Programs */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <section className="space-y-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2 className="text-2xl font-bold flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Briefcase className="h-6 w-6" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Michigan Disability Services
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-muted-foreground text-sm">State-level programs, independent living centers, and advocacy services</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="grid gap-4 md:grid-cols-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {michiganPrograms.map((card) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <BenefitCardComponent key={card.label} card={card} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Separator />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Legal Help */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <section className="space-y-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h2 className="text-2xl font-bold flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Scale className="h-6 w-6" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Benefits Help & Legal Aid
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-muted-foreground text-sm">Free and low-cost legal help for disability-related issues</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="grid gap-4 md:grid-cols-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {legalHelp.map((card) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <BenefitCardComponent key={card.label} card={card} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Source Footer */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="rounded-lg bg-muted border p-4 text-sm text-muted-foreground">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="font-medium mb-2">Sources</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex flex-wrap gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {['SSA', 'MDHHS', 'MPAS', 'Michigan Legal Help', 'CMS', 'ADA.gov'].map((s) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Badge key={s} variant="outline">{s}</Badge>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Layout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }