import { test, expect, type ConsoleMessage } from '@playwright/test';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

// Extract static route paths from src/config/routes.ts by regex so we don't
// have to execute the module (which imports lazy React components).
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROUTES_FILE = join(__dirname, '../../config/routes.ts');

function extractPaths(): string[] {
  const text = readFileSync(ROUTES_FILE, 'utf8');
  // Match lines like: { path: "/foo", component: ... }
  const re = /\{\s*path:\s*"([^"]+)"/g;
  const paths = new Set<string>();
  let m: RegExpExecArray | null;
  while ((m = re.exec(text)) !== null) {
    const p = m[1];
    // Skip dynamic params for this smoke sweep — they need fixtures
    if (p.includes(':')) continue;
    paths.add(p);
  }
  return [...paths];
}

// Dynamic routes we DO want to smoke-test, with a representative value
const DYNAMIC_SMOKE_PATHS = [
  '/zip/48201',
  '/county/wayne',
  '/place/detroit',
];

const ALL_PATHS = [...extractPaths(), ...DYNAMIC_SMOKE_PATHS];

type Failure = {
  path: string;
  reason: string;
  detail: string;
};

const failures: Failure[] = [];

test.describe.configure({ mode: 'parallel' });

test.describe('All routes smoke test', () => {
  for (const path of ALL_PATHS) {
    test(`renders ${path}`, async ({ page }) => {
      const consoleErrors: string[] = [];
      const pageErrors: string[] = [];

      page.on('console', (msg: ConsoleMessage) => {
        if (msg.type() === 'error') {
          const t = msg.text();
          // Ignore known noisy third-party warnings
          if (/Failed to load resource|net::ERR_|favicon|source-map/i.test(t)) return;
          consoleErrors.push(t);
        }
      });
      page.on('pageerror', (err) => pageErrors.push(String(err)));

      let navOk = true;
      try {
        await page.goto(path, { waitUntil: 'domcontentloaded', timeout: 20000 });
      } catch (err) {
        navOk = false;
        failures.push({ path, reason: 'navigation', detail: String(err) });
        test.fail(true, `Failed to navigate to ${path}`);
        return;
      }

      // Wait for app shell to settle
      await page.waitForLoadState('networkidle', { timeout: 20000 }).catch(() => {});

      // Assert no visible ErrorBoundary fallback
      const errorText = await page.locator('text=/Something went wrong/i').count();
      if (errorText > 0) {
        failures.push({ path, reason: 'error-boundary', detail: 'Rendered "Something went wrong"' });
      }
      expect(errorText, 'ErrorBoundary fallback should not render').toBe(0);

      // At least one heading
      const headingCount = await page.locator('h1, h2').count();
      if (headingCount === 0) {
        failures.push({ path, reason: 'no-heading', detail: 'No h1/h2 on page' });
      }
      expect(headingCount, 'Expected at least one h1/h2').toBeGreaterThan(0);

      // Title is set
      const title = await page.title();
      expect(title.length, 'Expected non-empty <title>').toBeGreaterThan(0);

      if (pageErrors.length > 0) {
        failures.push({ path, reason: 'page-error', detail: pageErrors.join(' | ') });
      }
      expect(pageErrors, `Uncaught page errors: ${pageErrors.join(' | ')}`).toHaveLength(0);

      if (consoleErrors.length > 0) {
        // Log but don't fail on console errors (often noisy third-party warnings)
        failures.push({ path, reason: 'console-error', detail: consoleErrors.join(' | ') });
      }
    });
  }

  test.afterAll(() => {
    if (failures.length === 0) return;
    const out = [
      '# Failed Routes',
      '',
      `Generated by all-routes.spec.ts at ${new Date().toISOString()}`,
      '',
      '| Path | Reason | Detail |',
      '| --- | --- | --- |',
      ...failures.map(f => `| ${f.path} | ${f.reason} | ${f.detail.replace(/\|/g, '\\|').slice(0, 200)} |`),
    ].join('\n');
    const target = join(__dirname, '../../../FAILED_ROUTES.md');
    try {
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, out, 'utf8');
    } catch {
      // best-effort
    }
  });
});
