import { motion } from "framer-motion";
import Layout from "@/components/layout/Layout";
import Breadcrumbs from "@/components/layout/Breadcrumbs";
import { Separator } from "@/components/ui/separator";
import { usePageMeta } from "@/hooks/usePageMeta";
import { FileText, Shield, AlertTriangle, Scale, Globe, Mail } from "lucide-react";
import { Link } from "react-router-dom";

const fade = {
  hidden: { opacity: 0, y: 16 },
  visible: (i: number) => ({ opacity: 1, y: 0, transition: { delay: i * 0.06, duration: 0.45 } }),
};

export default function TermsPage() {
  usePageMeta({
    title: "Terms of Use | Access Michigan",
    description:
      "Terms and conditions for using Access Michigan, including disclaimers, limitation of liability, and acceptable use policies.",
    path: "/terms",
  });

  const effectiveDate = "February 25, 2025";

  return (
    <Layout>
      <section className="bg-gradient-to-b from-primary/5 to-background py-16 lg:py-24">
        <div className="container max-w-4xl text-center">
          <Breadcrumbs items={[{ label: "Terms of Use" }]} />
          <motion.h1 variants={fade} custom={1} initial="hidden" animate="visible" className="mb-4 text-3xl font-bold text-foreground lg:text-5xl">
            Terms of Use
          </motion.h1>
          <motion.p variants={fade} custom={2} initial="hidden" animate="visible" className="mx-auto max-w-2xl text-lg text-muted-foreground">
            By using Access Michigan you agree to these terms. Please read them carefully.
          </motion.p>
          <motion.p variants={fade} custom={3} initial="hidden" animate="visible" className="mt-4 text-sm text-muted-foreground">
            <strong>Effective Date:</strong> {effectiveDate}
          </motion.p>
        </div>
      </section>

      <div className="container max-w-4xl py-12 space-y-14">

        <Section icon={Globe} title="1. About This Platform" i={0}>
          <p>
            Access Michigan is a free, non-commercial civic resource created to help Michigan residents navigate healthcare, social services, and community programs. It is <strong>not affiliated with, endorsed by, or operated by</strong> any government agency, healthcare provider, health plan, or insurance company.
          </p>
        </Section>

        <Separator />

        <Section icon={AlertTriangle} title="2. Not Medical, Legal, or Insurance Advice" i={1}>
          <div className="rounded-xl border-2 border-michigan-coral/30 bg-michigan-coral/5 p-6">
            <p className="font-semibold text-foreground mb-2">Important Disclaimer</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Content on Access Michigan is <strong>informational only</strong> and does not constitute medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider for medical decisions.</li>
              <li>Insurance appeal letters generated by AI are <strong>templates and starting points</strong>. They do not guarantee claim approval and should be reviewed by a healthcare provider or legal professional before submission.</li>
              <li>Financial eligibility information is <strong>approximate</strong>. Actual eligibility is determined by the administering agency.</li>
              <li>Facility and provider data is sourced from public databases and may not reflect real-time availability, hours, or acceptance of your insurance plan.</li>
            </ul>
          </div>
        </Section>

        <Separator />

        <Section icon={Shield} title="3. Accuracy & Data Sources" i={2}>
          <p>
            We aggregate data from federal and state public sources (CMS, HRSA, CDC, MDHHS, and others) and present it in a user-friendly format. While we strive for accuracy:
          </p>
          <ul className="list-disc pl-6 space-y-2 mt-3">
            <li>Data may be outdated due to source update schedules (see <Link to="/data-validation" className="text-primary hover:underline">Data Sources</Link> for cadences).</li>
            <li>Modeled or estimated values are always labeled as such.</li>
            <li>We do not independently verify all provider or facility details.</li>
            <li>Users should confirm critical details (insurance acceptance, hours, availability) directly with providers.</li>
          </ul>
        </Section>

        <Separator />

        <Section icon={FileText} title="4. Acceptable Use" i={3}>
          <p>You agree not to:</p>
          <ul className="list-disc pl-6 space-y-2 mt-2">
            <li>Use automated tools to scrape, crawl, or extract data at scale without permission.</li>
            <li>Attempt to compromise the security or availability of the Platform.</li>
            <li>Submit false information through contact forms or resource submission tools.</li>
            <li>Use AI-generated content (appeal letters, chat responses) in ways that misrepresent its source or nature.</li>
            <li>Use the Platform for commercial purposes, reselling data, or competitive intelligence.</li>
          </ul>
        </Section>

        <Separator />

        <Section icon={Scale} title="5. Limitation of Liability" i={4}>
          <p>
            Access Michigan is provided <strong>"as is" and "as available"</strong> without warranties of any kind, express or implied, including but not limited to warranties of accuracy, completeness, fitness for a particular purpose, or non-infringement.
          </p>
          <p className="mt-3">
            In no event shall Access Michigan, its creators, contributors, or hosting providers be liable for any direct, indirect, incidental, consequential, or special damages arising from:
          </p>
          <ul className="list-disc pl-6 space-y-1.5 mt-2">
            <li>Use or inability to use the Platform.</li>
            <li>Reliance on any information provided by the Platform or AI-generated content.</li>
            <li>Actions taken based on facility, provider, or program information displayed.</li>
            <li>Service interruptions, data inaccuracies, or technical errors.</li>
          </ul>
        </Section>

        <Separator />

        <Section icon={Globe} title="6. Intellectual Property" i={5}>
          <p>
            Original content, design, and code of Access Michigan are the property of its creator. Public data sourced from government agencies remains in the public domain. Third-party trademarks (hospital names, program names, agency names) belong to their respective owners and are used for informational purposes only.
          </p>
        </Section>

        <Separator />

        <Section icon={Shield} title="7. External Links" i={6}>
          <p>
            Access Michigan links to external websites (government agencies, healthcare providers, community organizations). We are not responsible for the content, privacy practices, or availability of external sites. Linking does not imply endorsement.
          </p>
        </Section>

        <Separator />

        <Section icon={Scale} title="8. Governing Law" i={7}>
          <p>
            These Terms are governed by the laws of the State of Michigan, United States, without regard to conflict of law principles. Any disputes shall be resolved in the courts of the State of Michigan.
          </p>
        </Section>

        <Separator />

        <Section icon={FileText} title="9. Changes to These Terms" i={8}>
          <p>
            We may update these Terms from time to time. Continued use of the Platform after changes constitutes acceptance of the revised Terms. Material changes will be noted on the <Link to="/changelog" className="text-primary hover:underline">changelog</Link>.
          </p>
        </Section>

        <Separator />

        <motion.section initial="hidden" whileInView="visible" viewport={{ once: true }} variants={fade} custom={0}>
          <div className="rounded-2xl border border-primary/20 bg-primary/5 p-8 lg:p-12 text-center">
            <Mail className="mx-auto mb-4 h-8 w-8 text-primary" />
            <h2 className="text-2xl font-bold text-foreground mb-3">Questions?</h2>
            <p className="text-muted-foreground leading-relaxed max-w-xl mx-auto mb-6">
              If you have questions about these Terms of Use, please reach out.
            </p>
            <Link
              to="/contact"
              className="inline-flex items-center gap-2 rounded-lg bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground hover:opacity-90 transition-opacity"
            >
              <Mail className="h-4 w-4" />
              Contact Us
            </Link>
          </div>
        </motion.section>
      </div>
    </Layout>
  );
}

function Section({ icon: Icon, title, i, children }: { icon: React.ElementType; title: string; i: number; children: React.ReactNode }) {
  return (
    <motion.section initial="hidden" whileInView="visible" viewport={{ once: true }} variants={fade} custom={i}>
      <div className="flex items-center gap-3 mb-5">
        <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
          <Icon className="h-5 w-5 text-primary" />
        </div>
        <h2 className="text-xl font-bold text-foreground lg:text-2xl">{title}</h2>
      </div>
      <div className="space-y-3 text-sm text-muted-foreground leading-relaxed">
        {children}
      </div>
    </motion.section>
  );
}
