import { FileText, DollarSign, Gavel, ExternalLink } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import Layout from '@/components/layout/Layout';

interface TransCard {
  label: string;
    desc: string;
      link: string;
        badge: string;
        }

        const foiaCards: TransCard[] = [
          {
              label: "Michigan Secretary of State – FOIA Portal",
                  desc: "Submit public records requests to Michigan state agencies and search previously released records through the SOS's centralized FOIA portal.",
                      link: "https://www.michigan.gov/sos",
                          badge: "Michigan Secretary of State"
                            },
                              {
                                  label: "Your Rights Under Michigan FOIA",
                                      desc: "Every Michigan resident has the right to request public records from state and local government agencies. The AG's office explains timelines, fees, and how to appeal denials.",
                                          link: "https://www.michigan.gov/ag/consumer-protection/citizen-guide-to-foia",
                                              badge: "Michigan Attorney General"
                                                },
                                                  {
                                                      label: "MuckRock – Michigan FOIA Requests",
                                                          desc: "MuckRock is a nonpartisan platform that helps people file FOIA requests and publishes responses. Search Michigan-specific requests and documents.",
                                                              link: "https://www.muckrock.com/place/united-states/michigan/",
                                                                  badge: "MuckRock (nonpartisan)"
                                                                    }
                                                                    ];

                                                                    const spendingCards: TransCard[] = [
                                                                      {
                                                                          label: "Michigan Transparency Portal",
                                                                              desc: "Official state portal for searching state expenditures, vendor contracts, grants, and state employee compensation data.",
                                                                                  link: "https://www.michigan.gov/transparency",
                                                                                      badge: "State of Michigan"
                                                                                        },
                                                                                          {
                                                                                              label: "Michigan Budget",
                                                                                                  desc: "The Governor's recommended budget and enacted appropriations by department and fiscal year, published by the State Budget Office.",
                                                                                                      link: "https://www.michigan.gov/budget",
                                                                                                          badge: "State Budget Office"
                                                                                                            },
                                                                                                              {
                                                                                                                  label: "Michigan Campaign Finance",
                                                                                                                      desc: "Search campaign finance filings for Michigan candidates and committees through the Secretary of State's campaign finance database.",
                                                                                                                          link: "https://www.michigan.gov/sos/elections/campaign-finance",
                                                                                                                              badge: "Michigan Secretary of State"
                                                                                                                                }
                                                                                                                                ];

                                                                                                                                const legalCards: TransCard[] = [
                                                                                                                                  {
                                                                                                                                      label: "Michigan Legislature – Bills & Laws",
                                                                                                                                          desc: "Track Michigan legislation, committee hearings, and session schedules through the official legislative website.",
                                                                                                                                              link: "https://www.legislature.mi.gov",
                                                                                                                                                  badge: "Michigan Legislature"
                                                                                                                                                    },
                                                                                                                                                      {
                                                                                                                                                          label: "Michigan Court Records – EFTS",
                                                                                                                                                              desc: "Search public court case records through the Michigan Court Electronic Filing and Track System.",
                                                                                                                                                                  link: "https://www.courts.michigan.gov",
                                                                                                                                                                      badge: "Michigan Supreme Court"
                                                                                                                                                                        },
                                                                                                                                                                          {
                                                                                                                                                                              label: "U.S. Federal Spending – USASpending.gov",
                                                                                                                                                                                  desc: "Search federal contracts, grants, and spending flowing to Michigan recipients using the federal transparency portal.",
                                                                                                                                                                                      link: "https://www.usaspending.gov/search?filters=%7B%22recipient_locations%22%3A%5B%7B%22country%22%3A%22USA%22%2C%22state%22%3A%22MI%22%7D%5D%7D",
                                                                                                                                                                                          badge: "USASpending.gov · OMB"
                                                                                                                                                                                            }
                                                                                                                                                                                            ];

                                                                                                                                                                                            function TransCardComponent({ card }: { card: TransCard }) {
                                                                                                                                                                                              return (
                                                                                                                                                                                                  <Card>
                                                                                                                                                                                                        <CardHeader>
                                                                                                                                                                                                                <CardTitle className="text-lg">{card.label}</CardTitle>
                                                                                                                                                                                                                        <CardDescription className="text-sm leading-relaxed">{card.desc}</CardDescription>
                                                                                                                                                                                                                              </CardHeader>
                                                                                                                                                                                                                                    <CardContent className="space-y-2">
                                                                                                                                                                                                                                            <Button asChild className="w-full bg-michigan-blue hover:bg-michigan-blue/90" size="sm">
                                                                                                                                                                                                                                                      <a href={card.link} target="_blank" rel="noopener noreferrer">
                                                                                                                                                                                                                                                                  Access <ExternalLink className="h-3 w-3 ml-2" />
                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                    </Button>
                                                                                                                                                                                                                                                                                            <Badge variant="secondary" className="w-full justify-center text-xs">{card.badge}</Badge>
                                                                                                                                                                                                                                                                                                  </CardContent>
                                                                                                                                                                                                                                                                                                      </Card>
                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                        export default function TransparencyPage() {
                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                              <Layout title="Transparency & Public Records" description="Michigan FOIA tools, state spending data, and legislative transparency resources">
                                                                                                                                                                                                                                                                                                                    <div className="min-h-screen bg-background">
                                                                                                                                                                                                                                                                                                                            {/* Header */}
                                                                                                                                                                                                                                                                                                                                    <div className="border-b bg-muted/30">
                                                                                                                                                                                                                                                                                                                                              <div className="container max-w-4xl py-12 space-y-4">
                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                        <FileText className="h-10 w-10 text-michigan-blue" />
                                                                                                                                                                                                                                                                                                                                                                                      <h1 className="text-4xl font-bold">Transparency & Public Records</h1>
                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-lg text-muted-foreground max-w-2xl">
                                                                                                                                                                                                                                                                                                                                                                                                                            Request Michigan government records, search state spending, and track legislation through official public portals.
                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="container max-w-4xl py-12 space-y-12">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* FOIA Tools */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <section className="space-y-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="text-2xl font-bold flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <FileText className="h-6 w-6" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Request Michigan Government Records (FOIA)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {foiaCards.map((card) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <TransCardComponent key={card.label} card={card} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Separator />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Spending */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <section className="space-y-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="text-2xl font-bold flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <DollarSign className="h-6 w-6" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                State Spending, Contracts & Salaries
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {spendingCards.map((card) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <TransCardComponent key={card.label} card={card} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Separator />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Courts & Legislature */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <section className="space-y-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="text-2xl font-bold flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Gavel className="h-6 w-6" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Legislation, Courts & Records
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {legalCards.map((card) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <TransCardComponent key={card.label} card={card} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Disclaimer */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="rounded-lg bg-amber-50 border border-amber-200 p-4 text-sm text-amber-900">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Access Michigan links only to official government portals and publicly available databases.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    We do not collect, store, or transmit records request data.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Layout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }