import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Loader2 } from "lucide-react";

type NarrativeRole = "resident" | "strategist";

interface ZIPNarrativesProps {
  zip: string;
  county: string;
  equityScore: number;
  equityTier: number;
  topHealthConcern: string;
  medianIncome: number;
  renterPct: number;
  lepPct: number;
  disabilityPct: number;
}

export default function ZIPNarratives({
  zip, county, equityScore, equityTier, topHealthConcern,
  medianIncome, renterPct, lepPct, disabilityPct,
}: ZIPNarrativesProps) {
  const [activeRole, setActiveRole] = useState<NarrativeRole>("resident");
  const [narratives, setNarratives] = useState<Record<NarrativeRole, string>>({ resident: "", strategist: "" });
  const [loading, setLoading] = useState(false);
  const [generated, setGenerated] = useState(false);

  const PROMPTS: Record<NarrativeRole, string> = {
    resident: `Write a 2-paragraph plain-language summary for a resident of ZIP code ${zip} in ${county} County, Michigan. Population data: Equity score ${equityScore}/100 (Tier ${equityTier}). Top health concern: ${topHealthConcern}. Median income: $${medianIncome.toLocaleString()}. Write in second person. Focus on available resources. Empathetic, action-oriented. Under 120 words. Do not mention race. Label data with source year.`,
    strategist: `Write a 2-paragraph professional summary for a hospital system strategist reviewing ZIP ${zip} in ${county} County, Michigan. Equity score ${equityScore}/100 (Tier ${equityTier}). Top concern: ${topHealthConcern}. Renter rate: ${renterPct.toFixed(1)}%. LEP: ${lepPct.toFixed(1)}%. Focus on market opportunity, care gap analysis, community benefit strategy. Professional tone. Under 130 words.`,
  };

  const generateNarratives = async () => {
    setLoading(true);
    try {
      const results: Record<NarrativeRole, string> = { resident: "", strategist: "" };
      for (const role of ["resident", "strategist"] as NarrativeRole[]) {
        try {
          const res = await fetch("/.netlify/functions/chat-mistral", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              messages: [{ role: "user", content: PROMPTS[role] }],
            }),
          });
          if (res.ok) {
            const data = await res.json();
            results[role] = data.reply || "";
          }
        } catch { /* skip failed role */ }
      }
      setNarratives(results);
      setGenerated(true);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-bold text-foreground">Community Narrative</h3>
        {!generated && (
          <button onClick={generateNarratives} disabled={loading}
            className="text-xs bg-primary text-primary-foreground px-3 py-1.5 rounded-lg hover:bg-primary/90 disabled:opacity-50 transition-colors inline-flex items-center gap-1.5">
            {loading ? <><Loader2 className="h-3 w-3 animate-spin" /> Generating...</> : "Generate Narrative"}
          </button>
        )}
      </div>

      {generated && (
        <>
          <div className="flex gap-1">
            {([
              { key: "resident" as const, label: "For Residents", icon: "\u{1F464}" },
              { key: "strategist" as const, label: "For Health Systems", icon: "\u{1F3E5}" },
            ]).map(({ key, label, icon }) => (
              <button key={key} onClick={() => setActiveRole(key)}
                className={`flex-1 text-[10px] py-1.5 px-2 rounded-lg border transition-all ${activeRole === key ? "bg-primary text-primary-foreground border-primary" : "bg-background border-border text-muted-foreground hover:bg-muted"}`}>
                {icon} {label}
              </button>
            ))}
          </div>
          <AnimatePresence mode="wait">
            <motion.div key={activeRole} initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -4 }}
              className="rounded-lg bg-muted/40 border border-border p-4">
              <p className="text-sm text-foreground leading-relaxed whitespace-pre-wrap">{narratives[activeRole] || "Narrative unavailable."}</p>
              <p className="text-[9px] text-muted-foreground mt-2">AI-generated summary using verified public data. Not a substitute for clinical or policy judgment. Generated by Mistral AI.</p>
            </motion.div>
          </AnimatePresence>
          <button onClick={generateNarratives} disabled={loading} className="text-[10px] text-muted-foreground hover:text-foreground transition-colors">
            {loading ? "Generating..." : "\u21BB Regenerate"}
          </button>
        </>
      )}

      {!generated && !loading && (
        <p className="text-[9px] text-muted-foreground">Click "Generate Narrative" to create AI-powered community summaries for residents and health systems.</p>
      )}
    </div>
  );
}
