/**
 * Discoverability integrity tests.
 *
 * Sitemap: validates public/sitemap.xml (generated by generate-sitemap.mjs)
 * JSON-LD:  validates dist/ prerendered HTML for route-specific structured data
 *           (generated by prerender-meta.mjs + injectRouteJsonLd). Skipped if
 *           dist/ is absent  -  runs after `npm run build`.
 */
import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(here, "../../..");

// ---------------------------------------------------------------------------
// Sitemap  -  always available (public/ is tracked in git)
// ---------------------------------------------------------------------------

const sitemapPath = path.join(projectRoot, "public/sitemap.xml");

describe("sitemap.xml", () => {
  let xml: string;
  let locs: string[];

  it("file exists", () => {
    expect(existsSync(sitemapPath)).toBe(true);
    xml = readFileSync(sitemapPath, "utf8");
    locs = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);
  });

  it("all <loc> entries start with https://accessmi.org", () => {
    xml ??= readFileSync(sitemapPath, "utf8");
    locs ??= [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);
    const bad = locs.filter((u) => !u.startsWith("https://accessmi.org"));
    expect(bad).toHaveLength(0);
  });

  it("has exactly 83 /county/ routes", () => {
    xml ??= readFileSync(sitemapPath, "utf8");
    locs ??= [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);
    const countyRoutes = locs.filter((u) => u.includes("/county/"));
    expect(countyRoutes).toHaveLength(83);
  });

  it("has exactly 83 /brief?county= canonicals", () => {
    xml ??= readFileSync(sitemapPath, "utf8");
    locs ??= [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);
    const briefRoutes = locs.filter((u) => u.includes("/brief?county="));
    expect(briefRoutes).toHaveLength(83);
  });

  it("has no duplicate <loc> entries", () => {
    xml ??= readFileSync(sitemapPath, "utf8");
    locs ??= [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);
    const unique = new Set(locs);
    expect(unique.size).toBe(locs.length);
  });

  it("lastmod values are YYYY-MM-DD (no raw ISO timestamps)", () => {
    xml ??= readFileSync(sitemapPath, "utf8");
    const lastmods = [...xml.matchAll(/<lastmod>([^<]+)<\/lastmod>/g)].map(
      (m) => m[1],
    );
    expect(lastmods.length).toBeGreaterThan(0);
    const bad = lastmods.filter((d) => !/^\d{4}-\d{2}-\d{2}$/.test(d));
    expect(bad).toHaveLength(0);
  });

  it("includes /county/wayne and /county/keweenaw", () => {
    xml ??= readFileSync(sitemapPath, "utf8");
    locs ??= [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);
    expect(locs).toContain("https://accessmi.org/county/wayne");
    expect(locs).toContain("https://accessmi.org/county/keweenaw");
  });

  it("includes /county/grand-traverse and /county/st-clair (multi-word slugs)", () => {
    xml ??= readFileSync(sitemapPath, "utf8");
    locs ??= [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);
    expect(locs).toContain("https://accessmi.org/county/grand-traverse");
    expect(locs).toContain("https://accessmi.org/county/st-clair");
  });
});

// ---------------------------------------------------------------------------
// JSON-LD in prerendered dist/ files
// Skip gracefully if dist/ hasn't been built yet in the current environment.
// ---------------------------------------------------------------------------

function parseJsonLdBlocks(html: string): unknown[] {
  const blocks: unknown[] = [];
  const re = /<script type="application\/ld\+json">([\s\S]*?)<\/script>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(html)) !== null) {
    try {
      blocks.push(JSON.parse(m[1]));
    } catch {
      // skip malformed
    }
  }
  return blocks;
}

const distDir = path.join(projectRoot, "dist");

const describeIfDist = existsSync(distDir) ? describe : describe.skip;

describeIfDist("dist/data-sources/index.html JSON-LD", () => {
  const filePath = path.join(distDir, "data-sources/index.html");
  let blocks: unknown[];

  it("file exists", () => {
    expect(existsSync(filePath)).toBe(true);
    blocks = parseJsonLdBlocks(readFileSync(filePath, "utf8"));
  });

  it("has at least one parseable JSON-LD block", () => {
    blocks ??= parseJsonLdBlocks(readFileSync(filePath, "utf8"));
    expect(blocks.length).toBeGreaterThan(0);
  });

  it("contains a DataCatalog block", () => {
    blocks ??= parseJsonLdBlocks(readFileSync(filePath, "utf8"));
    const catalog = blocks.find(
      (b) => (b as Record<string, unknown>)["@type"] === "DataCatalog",
    );
    expect(catalog).toBeDefined();
  });

  it("DataCatalog license points to /methodology", () => {
    blocks ??= parseJsonLdBlocks(readFileSync(filePath, "utf8"));
    const catalog = blocks.find(
      (b) => (b as Record<string, unknown>)["@type"] === "DataCatalog",
    ) as Record<string, unknown> | undefined;
    expect(catalog?.license).toMatch(/\/methodology$/);
  });

  it("DataCatalog creator is not GovernmentOrganization", () => {
    blocks ??= parseJsonLdBlocks(readFileSync(filePath, "utf8"));
    for (const b of blocks) {
      const block = b as Record<string, unknown>;
      if (block["@type"] === "DataCatalog") {
        const creator = block["creator"] as Record<string, unknown> | undefined;
        expect(creator?.["@type"]).not.toBe("GovernmentOrganization");
      }
    }
  });

  it("no block uses GovernmentOrganization type", () => {
    blocks ??= parseJsonLdBlocks(readFileSync(filePath, "utf8"));
    const raw = readFileSync(filePath, "utf8");
    const jsonLdSections = [
      ...raw.matchAll(
        /<script type="application\/ld\+json">([\s\S]*?)<\/script>/g,
      ),
    ].map((m) => m[1]);
    for (const section of jsonLdSections) {
      expect(section).not.toContain("GovernmentOrganization");
    }
  });
});

describeIfDist("dist/brief/index.html JSON-LD", () => {
  const filePath = path.join(distDir, "brief/index.html");
  let blocks: unknown[];

  it("file exists", () => {
    expect(existsSync(filePath)).toBe(true);
    blocks = parseJsonLdBlocks(readFileSync(filePath, "utf8"));
  });

  it("has at least one parseable JSON-LD block", () => {
    blocks ??= parseJsonLdBlocks(readFileSync(filePath, "utf8"));
    expect(blocks.length).toBeGreaterThan(0);
  });

  it("contains a Dataset block", () => {
    blocks ??= parseJsonLdBlocks(readFileSync(filePath, "utf8"));
    const dataset = blocks.find(
      (b) => (b as Record<string, unknown>)["@type"] === "Dataset",
    );
    expect(dataset).toBeDefined();
  });

  it("Dataset license points to /methodology", () => {
    blocks ??= parseJsonLdBlocks(readFileSync(filePath, "utf8"));
    const dataset = blocks.find(
      (b) => (b as Record<string, unknown>)["@type"] === "Dataset",
    ) as Record<string, unknown> | undefined;
    expect(dataset?.license).toMatch(/\/methodology$/);
  });

  it("Dataset creator is not GovernmentOrganization", () => {
    blocks ??= parseJsonLdBlocks(readFileSync(filePath, "utf8"));
    for (const b of blocks) {
      const block = b as Record<string, unknown>;
      if (block["@type"] === "Dataset") {
        const creator = block["creator"] as Record<string, unknown> | undefined;
        expect(creator?.["@type"]).not.toBe("GovernmentOrganization");
      }
    }
  });
});
