/**
 * Typed accessor for the ACS 5-Year county SDOH bundle. The JSON payload
 * lives in acs-sdoh-county.generated.json so the fixture is diffable and the
 * vintage can be read at build time without touching this shim.
 * Regenerated by scripts/refresh-acs-sdoh-county.mjs; do not hand-edit.
 */
import raw from "./acs-sdoh-county.generated.json";

export type AcsSdohMeasureId =
  | "povertyPct"
  | "childPovertyPct"
  | "rentBurden30Pct"
  | "ownerCostBurden30Pct"
  | "noVehicleHouseholdsPct"
  | "longCommute45Pct"
  | "noHsDiplomaPct"
  | "bachelorsPlusPct"
  | "limitedEnglishHouseholdsPct"
  | "crowdedHouseholdsPct"
  | "renterHouseholdsPct";

export interface AcsSdohMeasure {
  id: AcsSdohMeasureId;
  label: string;
  tables: string[];
  numerator: string[];
  universe: string[];
  excluded: string[];
  universeLabel: string;
  unit: "percent";
  value_label: "VERIFIED";
}

export interface AcsSdohCountyRecord {
  countyFips: string;
  countyName: string;
  /** "populated" when Census values are present; "pending-ci" when the
   * ingest environment lacked CENSUS_API_KEY and build-data.yml must re-run. */
  status: "populated" | "pending-ci";
  /** Percent (one decimal) per measure, or null when Census suppressed it. */
  values: Record<AcsSdohMeasureId, number | null>;
  pendingReason: string | null;
}

export interface AcsSdohCountyProvenance {
  source_name: string;
  source_url: string;
  api_base: string;
  dataset: string;
  vintage_window: string;
  tables: string[];
  table_urls: Record<string, string>;
  measure_count: number;
  ingested_at: string;
  ingest_script: string;
  michigan_county_registry: string;
  michigan_county_registry_size: number;
  value_label: "VERIFIED" | "PENDING";
  populated: boolean;
  pending_reason: string | null;
  notes: string;
}

interface Payload {
  provenance: AcsSdohCountyProvenance;
  measures: AcsSdohMeasure[];
  counties: AcsSdohCountyRecord[];
}

const payload = raw as Payload;

export const ACS_SDOH_COUNTY_PROVENANCE: AcsSdohCountyProvenance = payload.provenance;
export const ACS_SDOH_MEASURES: readonly AcsSdohMeasure[] = payload.measures;
export const ACS_SDOH_COUNTY_RECORDS: readonly AcsSdohCountyRecord[] = payload.counties;

const BY_FIPS = new Map<string, AcsSdohCountyRecord>(
  payload.counties.map((c) => [c.countyFips, c]),
);
const BY_NAME = new Map<string, AcsSdohCountyRecord>(
  payload.counties.map((c) => [c.countyName, c]),
);

export function getAcsSdohForCountyFips(fips: string): AcsSdohCountyRecord | null {
  return BY_FIPS.get(fips) ?? null;
}

export function getAcsSdohForCountyName(name: string): AcsSdohCountyRecord | null {
  return BY_NAME.get(name.replace(/\s+County$/i, "").trim()) ?? null;
}

/** One measure for one county, or null when pending or suppressed. */
export function getAcsSdohValue(
  countyName: string,
  measureId: AcsSdohMeasureId,
): number | null {
  const rec = getAcsSdohForCountyName(countyName);
  if (!rec || rec.status !== "populated") return null;
  return rec.values[measureId] ?? null;
}

/** True iff every county carries Census values. */
export const ACS_SDOH_IS_POPULATED = false;
