/**
 * Typed accessor for the CDC/ATSDR Social Vulnerability Index county file.
 * Payload in cdc-svi-county.generated.json; regenerated by
 * scripts/refresh-cdc-svi-county.mjs. Do not hand-edit.
 */
import raw from "./cdc-svi-county.generated.json";

export type SviThemeId =
  | "overall"
  | "socioeconomic"
  | "householdCharacteristics"
  | "racialEthnicMinority"
  | "housingTransportation";

export type SviInputId =
  | "belowPoverty150Pct"
  | "unemployedPct"
  | "housingCostBurdenPct"
  | "noHsDiplomaPct"
  | "uninsuredPct"
  | "age65PlusPct"
  | "age17UnderPct"
  | "disabilityPct"
  | "singleParentPct"
  | "limitedEnglishPct"
  | "minorityPct"
  | "multiUnitHousingPct"
  | "mobileHomesPct"
  | "crowdingPct"
  | "noVehiclePct"
  | "groupQuartersPct";

export interface SviCountyRecord {
  countyFips: string;
  countyName: string;
  status: "populated" | "pending-ci";
  /** US-wide county percentile ranks, 0 (least vulnerable) to 1 (most), or null. */
  themes: Record<SviThemeId, number | null>;
  /** ATSDR's ACS-derived input percentages (one decimal), or null. */
  inputs: Record<SviInputId, number | null>;
  pendingReason: string | null;
}

export interface SviCountyProvenance {
  source_name: string;
  source_url: string;
  download_url: string | null;
  csv_sha256: string | null;
  svi_year: number | null;
  candidate_years: number[];
  ranking_universe: string;
  ingested_at: string;
  ingest_script: string;
  michigan_county_registry: string;
  michigan_county_registry_size: number;
  value_label: "MODELED" | "PENDING";
  populated: boolean;
  pending_reason: string | null;
  notes: string;
}

interface Payload {
  provenance: SviCountyProvenance;
  themes: Array<{ id: SviThemeId; column: string; label: string; value_label: "MODELED" }>;
  inputs: Array<{ id: SviInputId; column: string; label: string; value_label: "MODELED" }>;
  counties: SviCountyRecord[];
}

const payload = raw as Payload;

export const SVI_COUNTY_PROVENANCE: SviCountyProvenance = payload.provenance;
export const SVI_THEMES = payload.themes;
export const SVI_INPUTS = payload.inputs;
export const SVI_COUNTY_RECORDS: readonly SviCountyRecord[] = payload.counties;

const BY_FIPS = new Map<string, SviCountyRecord>(payload.counties.map((c) => [c.countyFips, c]));
const BY_NAME = new Map<string, SviCountyRecord>(payload.counties.map((c) => [c.countyName, c]));

export function getSviForCountyFips(fips: string): SviCountyRecord | null {
  return BY_FIPS.get(fips) ?? null;
}

export function getSviForCountyName(name: string): SviCountyRecord | null {
  return BY_NAME.get(name.replace(/\s+County$/i, "").trim()) ?? null;
}

/** Overall SVI percentile as 0-100, or null while pending. */
export function getSviOverallPercentile(countyName: string): number | null {
  const rec = getSviForCountyName(countyName);
  const v = rec?.status === "populated" ? rec.themes.overall : null;
  return v === null || v === undefined ? null : Math.round(v * 1000) / 10;
}

export const SVI_IS_POPULATED = false;
