/**
 * Generated by scripts/refresh-snap-retailers.mjs. Do not edit by hand.
 * Re-run the script to regenerate.
 *
 * Source: USDA Food and Nutrition Service (FNS), Historical SNAP Retailer
 *   Locator Data 2005-2025 (bulk CSV release).
 *   https://www.fns.usda.gov/snap/retailer/data
 *
 * Metric: count of currently authorized SNAP food retailers in Michigan,
 *   per county, current snapshot (rows whose End Date is blank). Rate is
 *   per 10,000 residents against PEP V2024 population
 *   (see src/data/michigan-county-profiles.ts).
 *
 * Vintage: 2025-12. USDA's publication "as of December 31, 2025"; most
 *   recent Authorization Date in the current set is 2025-09-09. The label
 *   reflects the data's as-of date, not when the script was run.
 *
 * No suppression rule: this is a count of currently authorized businesses,
 *   not a rare health event. Zero-retailer counties (if any) render 0
 *   rather than blanking; no county was zero in the generating extract.
 *
 * County assignment uses the source's own `County` field, normalized
 *   case-insensitively and with periods stripped (so "ST CLAIR" matches
 *   "St. Clair"). The script asserts row conservation: the assigned
 *   per-county sum + dropped rows equals the total Michigan currently-
 *   authorized rows pulled.
 *
 * Aggregation totals captured at generation time:
 *   Total MI currently-authorized rows: 9225
 *   Assigned to a county: 9225
 *   Dropped (blank county): 0
 *   Dropped (unmatched county string): 0
 */

export const SNAP_VINTAGE = "2025-12";
export const SNAP_SOURCE = "USDA SNAP Retailer Locator";

export interface CountySnapRetailers {
  /** Count of currently authorized SNAP retailers in the county. */
  retailerCount: number;
  /**
   * Retailers per 10,000 residents, computed as
   * (retailerCount / PEP V2024 population) * 10,000.
   * Two decimal places. Always a number; this metric does not suppress.
   */
  ratePer10k: number;
}

export const COUNTY_SNAP_RETAILERS: Record<string, CountySnapRetailers> = {
  Alcona: { retailerCount: 13, ratePer10k: 12.24 },
  Alger: { retailerCount: 12, ratePer10k: 13.80 },
  Allegan: { retailerCount: 88, ratePer10k: 7.19 },
  Alpena: { retailerCount: 30, ratePer10k: 10.38 },
  Antrim: { retailerCount: 19, ratePer10k: 7.74 },
  Arenac: { retailerCount: 24, ratePer10k: 15.91 },
  Baraga: { retailerCount: 11, ratePer10k: 13.47 },
  Barry: { retailerCount: 44, ratePer10k: 6.87 },
  Bay: { retailerCount: 109, ratePer10k: 10.62 },
  Benzie: { retailerCount: 19, ratePer10k: 10.26 },
  Berrien: { retailerCount: 151, ratePer10k: 9.89 },
  Branch: { retailerCount: 49, ratePer10k: 10.61 },
  Calhoun: { retailerCount: 172, ratePer10k: 12.86 },
  Cass: { retailerCount: 36, ratePer10k: 6.98 },
  Charlevoix: { retailerCount: 26, ratePer10k: 9.96 },
  Cheboygan: { retailerCount: 24, ratePer10k: 9.24 },
  Chippewa: { retailerCount: 37, ratePer10k: 10.21 },
  Clare: { retailerCount: 54, ratePer10k: 17.19 },
  Clinton: { retailerCount: 45, ratePer10k: 5.62 },
  Crawford: { retailerCount: 22, ratePer10k: 16.18 },
  Delta: { retailerCount: 36, ratePer10k: 9.81 },
  Dickinson: { retailerCount: 26, ratePer10k: 10.00 },
  Eaton: { retailerCount: 97, ratePer10k: 8.86 },
  Emmet: { retailerCount: 34, ratePer10k: 10.02 },
  Genesee: { retailerCount: 418, ratePer10k: 10.39 },
  Gladwin: { retailerCount: 36, ratePer10k: 13.85 },
  Gogebic: { retailerCount: 22, ratePer10k: 15.47 },
  "Grand Traverse": { retailerCount: 75, ratePer10k: 7.76 },
  Gratiot: { retailerCount: 36, ratePer10k: 8.70 },
  Hillsdale: { retailerCount: 46, ratePer10k: 10.09 },
  Houghton: { retailerCount: 42, ratePer10k: 11.04 },
  Huron: { retailerCount: 39, ratePer10k: 12.67 },
  Ingham: { retailerCount: 232, ratePer10k: 7.99 },
  Ionia: { retailerCount: 60, ratePer10k: 9.06 },
  Iosco: { retailerCount: 40, ratePer10k: 15.77 },
  Iron: { retailerCount: 14, ratePer10k: 11.96 },
  Isabella: { retailerCount: 55, ratePer10k: 8.45 },
  Jackson: { retailerCount: 150, ratePer10k: 9.36 },
  Kalamazoo: { retailerCount: 210, ratePer10k: 7.93 },
  Kalkaska: { retailerCount: 23, ratePer10k: 12.35 },
  Kent: { retailerCount: 536, ratePer10k: 7.96 },
  Keweenaw: { retailerCount: 3, ratePer10k: 13.88 },
  Lake: { retailerCount: 19, ratePer10k: 14.61 },
  Lapeer: { retailerCount: 73, ratePer10k: 8.19 },
  Leelanau: { retailerCount: 14, ratePer10k: 6.12 },
  Lenawee: { retailerCount: 86, ratePer10k: 8.80 },
  Livingston: { retailerCount: 87, ratePer10k: 4.42 },
  Luce: { retailerCount: 10, ratePer10k: 15.80 },
  Mackinac: { retailerCount: 13, ratePer10k: 11.67 },
  Macomb: { retailerCount: 742, ratePer10k: 8.37 },
  Manistee: { retailerCount: 28, ratePer10k: 10.97 },
  Marquette: { retailerCount: 53, ratePer10k: 7.80 },
  Mason: { retailerCount: 36, ratePer10k: 12.37 },
  Mecosta: { retailerCount: 50, ratePer10k: 11.92 },
  Menominee: { retailerCount: 24, ratePer10k: 10.41 },
  Midland: { retailerCount: 66, ratePer10k: 7.86 },
  Missaukee: { retailerCount: 14, ratePer10k: 9.19 },
  Monroe: { retailerCount: 116, ratePer10k: 7.43 },
  Montcalm: { retailerCount: 84, ratePer10k: 12.12 },
  Montmorency: { retailerCount: 11, ratePer10k: 11.19 },
  Muskegon: { retailerCount: 171, ratePer10k: 9.64 },
  Newaygo: { retailerCount: 57, ratePer10k: 11.07 },
  Oakland: { retailerCount: 861, ratePer10k: 6.64 },
  Oceana: { retailerCount: 36, ratePer10k: 13.33 },
  Ogemaw: { retailerCount: 34, ratePer10k: 16.20 },
  Ontonagon: { retailerCount: 10, ratePer10k: 17.17 },
  Osceola: { retailerCount: 30, ratePer10k: 12.77 },
  Oscoda: { retailerCount: 12, ratePer10k: 13.96 },
  Otsego: { retailerCount: 38, ratePer10k: 14.57 },
  Ottawa: { retailerCount: 154, ratePer10k: 5.03 },
  "Presque Isle": { retailerCount: 14, ratePer10k: 10.58 },
  Roscommon: { retailerCount: 36, ratePer10k: 15.04 },
  Saginaw: { retailerCount: 199, ratePer10k: 10.60 },
  Sanilac: { retailerCount: 55, ratePer10k: 13.65 },
  Schoolcraft: { retailerCount: 7, ratePer10k: 8.56 },
  Shiawassee: { retailerCount: 58, ratePer10k: 8.53 },
  "St. Clair": { retailerCount: 160, ratePer10k: 9.98 },
  "St. Joseph": { retailerCount: 70, ratePer10k: 11.44 },
  Tuscola: { retailerCount: 52, ratePer10k: 9.86 },
  "Van Buren": { retailerCount: 90, ratePer10k: 11.82 },
  Washtenaw: { retailerCount: 225, ratePer10k: 6.02 },
  Wayne: { retailerCount: 2076, ratePer10k: 11.72 },
  Wexford: { retailerCount: 39, ratePer10k: 11.32 },
};
