/**
 * Generated by scripts/refresh-fars.mjs. Do not edit by hand. Re-run the
 * script to regenerate.
 *
 * Source: NHTSA Fatality Analysis Reporting System (FARS), bulk CSV release.
 * URL pattern:
 *   https://static.nhtsa.gov/nhtsa/downloads/FARS/{year}/National/FARS{year}NationalCSV.zip
 *
 * Metric: persons killed in fatal crashes (FARS accident.csv FATALS column),
 *   aggregated by Michigan county across the 5 most recent published case
 *   years.
 * Denominator: U.S. Census Bureau PEP V2024 (one named vintage applied
 *   across the window; see src/data/michigan-county-profiles.ts).
 * Suppression rule: counties with fewer than 6 fatal
 *   events across the 5-year window render the raw count (ratePer100k null,
 *   suppressed true) rather than a noisy per-100k rate. Threshold matches
 *   the MDHHS infant-mortality small-cell convention.
 *
 * Per-year Michigan totals captured at generation time:
 *   2020: 1086 persons killed in MI fatal crashes
 *   2021: 1137 persons killed in MI fatal crashes
 *   2022: 1124 persons killed in MI fatal crashes
 *   2023: 1096 persons killed in MI fatal crashes
 *   2024: 1098 persons killed in MI fatal crashes
 */

export const FARS_VINTAGE = "2020-2024";
export const FARS_SOURCE = "NHTSA FARS";
export const FARS_YEARS_INCLUDED = [2020, 2021, 2022, 2023, 2024] as const;
export const FARS_SUPPRESSION_THRESHOLD = 6;

export interface CountyTrafficFatalities {
  /** Sum of persons killed across the 5-year window. */
  fiveYearCount: number;
  /**
   * Average annual deaths per 100,000 residents, computed as
   * (fiveYearCount / (5 * PEP V2024 population)) * 100,000.
   * Null when the suppression rule applied.
   */
  ratePer100k: number | null;
  /** True when fiveYearCount fell below FARS_SUPPRESSION_THRESHOLD. */
  suppressed: boolean;
}

export const COUNTY_TRAFFIC_FATALITIES: Record<string, CountyTrafficFatalities> = {
  Alcona: { fiveYearCount: 11, ratePer100k: 20.7, suppressed: false },
  Alger: { fiveYearCount: 7, ratePer100k: 16.1, suppressed: false },
  Allegan: { fiveYearCount: 96, ratePer100k: 15.7, suppressed: false },
  Alpena: { fiveYearCount: 14, ratePer100k: 9.7, suppressed: false },
  Antrim: { fiveYearCount: 16, ratePer100k: 13.0, suppressed: false },
  Arenac: { fiveYearCount: 25, ratePer100k: 33.1, suppressed: false },
  Baraga: { fiveYearCount: 9, ratePer100k: 22.0, suppressed: false },
  Barry: { fiveYearCount: 42, ratePer100k: 13.1, suppressed: false },
  Bay: { fiveYearCount: 69, ratePer100k: 13.4, suppressed: false },
  Benzie: { fiveYearCount: 16, ratePer100k: 17.3, suppressed: false },
  Berrien: { fiveYearCount: 85, ratePer100k: 11.1, suppressed: false },
  Branch: { fiveYearCount: 27, ratePer100k: 11.7, suppressed: false },
  Calhoun: { fiveYearCount: 112, ratePer100k: 16.7, suppressed: false },
  Cass: { fiveYearCount: 59, ratePer100k: 22.9, suppressed: false },
  Charlevoix: { fiveYearCount: 17, ratePer100k: 13.0, suppressed: false },
  Cheboygan: { fiveYearCount: 18, ratePer100k: 13.9, suppressed: false },
  Chippewa: { fiveYearCount: 18, ratePer100k: 9.9, suppressed: false },
  Clare: { fiveYearCount: 29, ratePer100k: 18.5, suppressed: false },
  Clinton: { fiveYearCount: 43, ratePer100k: 10.7, suppressed: false },
  Crawford: { fiveYearCount: 7, ratePer100k: 10.3, suppressed: false },
  Delta: { fiveYearCount: 21, ratePer100k: 11.4, suppressed: false },
  Dickinson: { fiveYearCount: 21, ratePer100k: 16.2, suppressed: false },
  Eaton: { fiveYearCount: 72, ratePer100k: 13.2, suppressed: false },
  Emmet: { fiveYearCount: 20, ratePer100k: 11.8, suppressed: false },
  Genesee: { fiveYearCount: 280, ratePer100k: 13.9, suppressed: false },
  Gladwin: { fiveYearCount: 13, ratePer100k: 10.0, suppressed: false },
  Gogebic: { fiveYearCount: 1, ratePer100k: null, suppressed: true },
  "Grand Traverse": { fiveYearCount: 63, ratePer100k: 13.0, suppressed: false },
  Gratiot: { fiveYearCount: 35, ratePer100k: 16.9, suppressed: false },
  Hillsdale: { fiveYearCount: 30, ratePer100k: 13.2, suppressed: false },
  Houghton: { fiveYearCount: 16, ratePer100k: 8.4, suppressed: false },
  Huron: { fiveYearCount: 23, ratePer100k: 14.9, suppressed: false },
  Ingham: { fiveYearCount: 127, ratePer100k: 8.7, suppressed: false },
  Ionia: { fiveYearCount: 52, ratePer100k: 15.7, suppressed: false },
  Iosco: { fiveYearCount: 19, ratePer100k: 15.0, suppressed: false },
  Iron: { fiveYearCount: 14, ratePer100k: 23.9, suppressed: false },
  Isabella: { fiveYearCount: 54, ratePer100k: 16.6, suppressed: false },
  Jackson: { fiveYearCount: 118, ratePer100k: 14.7, suppressed: false },
  Kalamazoo: { fiveYearCount: 161, ratePer100k: 12.2, suppressed: false },
  Kalkaska: { fiveYearCount: 19, ratePer100k: 20.4, suppressed: false },
  Kent: { fiveYearCount: 303, ratePer100k: 9.0, suppressed: false },
  Keweenaw: { fiveYearCount: 2, ratePer100k: null, suppressed: true },
  Lake: { fiveYearCount: 8, ratePer100k: 12.3, suppressed: false },
  Lapeer: { fiveYearCount: 64, ratePer100k: 14.4, suppressed: false },
  Leelanau: { fiveYearCount: 10, ratePer100k: 8.7, suppressed: false },
  Lenawee: { fiveYearCount: 86, ratePer100k: 17.6, suppressed: false },
  Livingston: { fiveYearCount: 84, ratePer100k: 8.5, suppressed: false },
  Luce: { fiveYearCount: 4, ratePer100k: null, suppressed: true },
  Mackinac: { fiveYearCount: 16, ratePer100k: 28.7, suppressed: false },
  Macomb: { fiveYearCount: 286, ratePer100k: 6.5, suppressed: false },
  Manistee: { fiveYearCount: 24, ratePer100k: 18.8, suppressed: false },
  Marquette: { fiveYearCount: 24, ratePer100k: 7.1, suppressed: false },
  Mason: { fiveYearCount: 27, ratePer100k: 18.6, suppressed: false },
  Mecosta: { fiveYearCount: 33, ratePer100k: 15.7, suppressed: false },
  Menominee: { fiveYearCount: 20, ratePer100k: 17.4, suppressed: false },
  Midland: { fiveYearCount: 41, ratePer100k: 9.8, suppressed: false },
  Missaukee: { fiveYearCount: 9, ratePer100k: 11.8, suppressed: false },
  Monroe: { fiveYearCount: 105, ratePer100k: 13.5, suppressed: false },
  Montcalm: { fiveYearCount: 66, ratePer100k: 19.0, suppressed: false },
  Montmorency: { fiveYearCount: 2, ratePer100k: null, suppressed: true },
  Muskegon: { fiveYearCount: 103, ratePer100k: 11.6, suppressed: false },
  Newaygo: { fiveYearCount: 53, ratePer100k: 20.6, suppressed: false },
  Oakland: { fiveYearCount: 329, ratePer100k: 5.1, suppressed: false },
  Oceana: { fiveYearCount: 16, ratePer100k: 11.8, suppressed: false },
  Ogemaw: { fiveYearCount: 27, ratePer100k: 25.7, suppressed: false },
  Ontonagon: { fiveYearCount: 7, ratePer100k: 24.0, suppressed: false },
  Osceola: { fiveYearCount: 23, ratePer100k: 19.6, suppressed: false },
  Oscoda: { fiveYearCount: 19, ratePer100k: 44.2, suppressed: false },
  Otsego: { fiveYearCount: 21, ratePer100k: 16.1, suppressed: false },
  Ottawa: { fiveYearCount: 101, ratePer100k: 6.6, suppressed: false },
  "Presque Isle": { fiveYearCount: 9, ratePer100k: 13.6, suppressed: false },
  Roscommon: { fiveYearCount: 38, ratePer100k: 31.8, suppressed: false },
  Saginaw: { fiveYearCount: 101, ratePer100k: 10.8, suppressed: false },
  Sanilac: { fiveYearCount: 35, ratePer100k: 17.4, suppressed: false },
  Schoolcraft: { fiveYearCount: 8, ratePer100k: 19.6, suppressed: false },
  Shiawassee: { fiveYearCount: 46, ratePer100k: 13.5, suppressed: false },
  "St. Clair": { fiveYearCount: 116, ratePer100k: 14.5, suppressed: false },
  "St. Joseph": { fiveYearCount: 61, ratePer100k: 19.9, suppressed: false },
  Tuscola: { fiveYearCount: 39, ratePer100k: 14.8, suppressed: false },
  "Van Buren": { fiveYearCount: 65, ratePer100k: 17.1, suppressed: false },
  Washtenaw: { fiveYearCount: 137, ratePer100k: 7.3, suppressed: false },
  Wayne: { fiveYearCount: 1066, ratePer100k: 12.0, suppressed: false },
  Wexford: { fiveYearCount: 28, ratePer100k: 16.3, suppressed: false },
};
