/**
 * AUTO-GENERATED by scripts/ingest-ejscreen-csv.mjs
 * Source: data/fixtures/ejscreen-zcta-sample.csv
 * Generated: 2026-06-29T20:29:25.248Z
 * Records: 3
 *
 * Do not hand-edit. Re-run the ingest script to refresh.
 */

import type { EjscreenRecord } from "./ejscreen";

export const MICHIGAN_EJSCREEN_GENERATED: Record<string, EjscreenRecord> = {
  "48104": {
    "zcta": "48104",
    "ej_index": 52,
    "pm25_percentile": 45,
    "ozone_percentile": 48,
    "traffic_percentile": 52,
    "wastewater_percentile": 32,
    "rmp_percentile": 25,
    "pct_low_income": 18.2,
    "pct_minority": 22.6,
    "pct_less_hs": 3.8,
    "data_year": 2024
  },
  "48201": {
    "zcta": "48201",
    "ej_index": 88,
    "pm25_percentile": 78,
    "ozone_percentile": 72,
    "traffic_percentile": 88,
    "wastewater_percentile": 75,
    "rmp_percentile": 80,
    "pct_low_income": 42.1,
    "pct_minority": 82.4,
    "pct_less_hs": 18.3,
    "data_year": 2024
  },
  "49684": {
    "zcta": "49684",
    "ej_index": 38,
    "pm25_percentile": 28,
    "ozone_percentile": 35,
    "traffic_percentile": 38,
    "wastewater_percentile": 22,
    "rmp_percentile": 18,
    "pct_low_income": 14.6,
    "pct_minority": 6.2,
    "pct_less_hs": 5.4,
    "data_year": 2024
  }
};
