/**
 * Which USASpending program buckets can honestly be shown per county.
 *
 * USASpending attributes an award to the RECIPIENT's location. Michigan's
 * Medicaid and SNAP obligations are paid to state agencies in Lansing, so the
 * published data puts every one of those dollars in Ingham County and zero in
 * the 82 counties whose residents the programs actually serve. Rendering those
 * two buckets per county reads as "Wayne County gets $0 Medicaid", which is
 * false. They are shown as statewide totals instead.
 *
 * Kept out of federalSpending.ts on purpose: that file is generated by
 * scripts/refresh-usaspending-county.mjs.
 */
import {
  FEDERAL_SPENDING_BUCKETS,
  MICHIGAN_FEDERAL_SPENDING,
  type PopulatedCountyFederalSpending,
} from "./federalSpending";

export type StatewideField = "medicaid_millions" | "snap_millions";

export const STATEWIDE_ADMINISTERED_FIELDS: readonly StatewideField[] = [
  "medicaid_millions",
  "snap_millions",
];

export const STATEWIDE_ADMINISTERED_NOTE =
  "Medicaid and SNAP obligations are paid to state agencies in Lansing, so USASpending records them in Ingham County rather than in the counties served. They are reported here as statewide totals only, never as a county figure.";

/** Buckets whose recipients are genuinely local, safe to chart per county. */
export const COUNTY_ATTRIBUTABLE_BUCKETS = FEDERAL_SPENDING_BUCKETS.filter(
  (b) => !STATEWIDE_ADMINISTERED_FIELDS.includes(b.field as StatewideField),
);

export const STATEWIDE_ADMINISTERED_BUCKETS = FEDERAL_SPENDING_BUCKETS.filter((b) =>
  STATEWIDE_ADMINISTERED_FIELDS.includes(b.field as StatewideField),
);

/** Statewide total, in millions, for a bucket that cannot be split by county. */
export function statewideBucketTotal(field: StatewideField): number {
  return MICHIGAN_FEDERAL_SPENDING.reduce((sum, c) => sum + (c[field] ?? 0), 0);
}

export const STATEWIDE_ADMINISTERED_TOTALS = STATEWIDE_ADMINISTERED_BUCKETS.map((b) => ({
  field: b.field as StatewideField,
  label: b.label,
  millions: statewideBucketTotal(b.field as StatewideField),
}));

/**
 * County obligations excluding the statewide-administered buckets, so county
 * comparisons are not swamped by Lansing's state-agency payments.
 */
export function countyAttributableTotal(c: PopulatedCountyFederalSpending): number {
  return c.total_awards_millions - c.medicaid_millions - c.snap_millions;
}
