/**
 * Typed accessor for county-level federal award obligations.
 * Payload in usaspending-county.generated.json; regenerated by
 * scripts/refresh-usaspending-county.mjs. Do not hand-edit.
 *
 * Figures are USASpending.gov transaction obligations attributed to the
 * RECIPIENT's location, so statewide programs paid to a state agency sit in
 * that agency's county. Program buckets cover CFDA assistance listings only
 * and therefore do not sum to the county total. Both caveats are carried in
 * FEDERAL_SPENDING_PROVENANCE and must be surfaced wherever these figures
 * are rendered.
 */
import raw from "./usaspending-county.generated.json";

export interface FederalProgramShare {
  cfda: string;
  name: string;
  dollars: number;
}

export interface CountyFederalSpending {
  county: string;
  fips: string;
  status: "populated" | "pending-ci";
  /** Total federal obligations, in millions of dollars, or null when pending. */
  total_awards_millions: number | null;
  population: number | null;
  per_capita_dollars: number | null;
  medicaid_millions: number | null;
  snap_millions: number | null;
  housing_millions: number | null
  ;
  infrastructure_millions: number | null;
  health_grants_millions: number | null;
  education_millions: number | null;
  energy_millions: number | null;
  /** Sum of the CFDA-numbered dollars that landed in a bucket, in millions. */
  cfda_covered_millions: number | null;
  top_programs: FederalProgramShare[];
  fy: number | null;
  source: string;
  pending_reason?: string | null;
}

export interface FederalSpendingProvenance {
  source_name: string;
  source_url: string;
  api_endpoints: string[];
  fiscal_year: number | null;
  geography_basis: string;
  geography_caveat: string;
  program_bucket_basis: string;
  program_bucket_caveat: string;
  ingested_at: string;
  ingest_script: string;
  michigan_county_registry: string;
  michigan_county_registry_size: number;
  value_label: "VERIFIED" | "PENDING";
  populated: boolean;
  pending_reason: string | null;
  notes: string;
}

interface Payload {
  provenance: FederalSpendingProvenance;
  buckets: Array<{ field: string; label: string }>;
  counties: CountyFederalSpending[];
}

const payload = raw as unknown as Payload;

export const FEDERAL_SPENDING_PROVENANCE: FederalSpendingProvenance = payload.provenance;
export const FEDERAL_SPENDING_BUCKETS = payload.buckets;
export const FEDERAL_SPENDING_IS_POPULATED = true;

/**
 * A county whose figures came back from USASpending. Every numeric field is a
 * real published number here (0 is a real 0), which is why the pending rows
 * are filtered out rather than defaulted.
 */
export type PopulatedCountyFederalSpending = Omit<
  CountyFederalSpending,
  | "total_awards_millions"
  | "medicaid_millions"
  | "snap_millions"
  | "housing_millions"
  | "infrastructure_millions"
  | "health_grants_millions"
  | "education_millions"
  | "energy_millions"
  | "cfda_covered_millions"
  | "fy"
> & {
  total_awards_millions: number;
  medicaid_millions: number;
  snap_millions: number;
  housing_millions: number;
  infrastructure_millions: number;
  health_grants_millions: number;
  education_millions: number;
  energy_millions: number;
  cfda_covered_millions: number;
  fy: number;
};

function isPopulated(c: CountyFederalSpending): c is PopulatedCountyFederalSpending {
  return (
    c.status === "populated" &&
    c.total_awards_millions !== null &&
    c.medicaid_millions !== null &&
    c.snap_millions !== null &&
    c.housing_millions !== null &&
    c.infrastructure_millions !== null &&
    c.health_grants_millions !== null &&
    c.education_millions !== null &&
    c.energy_millions !== null &&
    c.cfda_covered_millions !== null &&
    c.fy !== null
  );
}

/** Every Michigan county with a published total, newest complete fiscal year. */
export const MICHIGAN_FEDERAL_SPENDING: PopulatedCountyFederalSpending[] =
  payload.counties.filter(isPopulated);

/** All 83 records including pending ones, for provenance and audit views. */
export const FEDERAL_SPENDING_ALL_COUNTIES: readonly CountyFederalSpending[] = payload.counties;

export function getCountyFederalSpending(county: string): CountyFederalSpending | null {
  const key = county.replace(/\s+County$/i, "").trim().toLowerCase();
  return payload.counties.find((c) => c.county.toLowerCase() === key) ?? null;
}

/**
 * Share of a county's federal obligations that arrives as safety-net
 * assistance (Medicaid, food, housing, energy), 0-100, or null when the
 * inputs are missing. This is a ratio of published figures, not a model of
 * county revenue: the previous "federal dependency" score was an unsourced
 * illustrative table and has been removed.
 */
export function getSafetyNetShare(county: string): number | null {
  const rec = getCountyFederalSpending(county);
  if (!rec || !isPopulated(rec) || rec.total_awards_millions === 0) return null;
  const sum =
    rec.medicaid_millions + rec.snap_millions + rec.housing_millions + rec.energy_millions;
  return Math.round((sum / rec.total_awards_millions) * 1000) / 10;
}

/**
 * Superseded name for the safety-net share. The old federal "dependency"
 * score was an unsourced illustrative table; this returns a ratio of
 * published obligations instead, or null when unknown.
 */
export function getFederalDependencyScore(county: string): number | null {
  return getSafetyNetShare(county);
}

/** Back-compat alias for the safety-net share. Returns null when unknown. */
export function n(county: string): number | null {
  return getSafetyNetShare(county);
}

