/**
 * Typed accessor for county-level federal award obligations.
 * Payload in usaspending-county.generated.json; regenerated by
 * scripts/refresh-usaspending-county.mjs. Do not hand-edit.
 *
 * Figures are USASpending.gov transaction obligations attributed to the
 * RECIPIENT's location, so statewide programs paid to a state agency sit in
 * that agency's county. Program buckets cover CFDA assistance listings only
 * and therefore do not sum to the county total. Both caveats are carried in
 * FEDERAL_SPENDING_PROVENANCE and must be surfaced wherever these figures
 * are rendered.
 */
import raw from "./usaspending-county.generated.json";

export interface FederalProgramShare {
  cfda: string;
  name: string;
  dollars: number;
}

export interface CountyFederalSpending {
  county: string;
  fips: string;
  status: "populated" | "pending-ci";
  /** Total federal obligations, in millions of dollars, or null when pending. */
  total_awards_millions: number | null;
  population: number | null;
  per_capita_dollars: number | null;
  medicaid_millions: number | null;
  snap_millions: number | null;
  housing_millions: number | null
  ;
  infrastructure_millions: number | null;
  health_grants_millions: number | null;
  education_millions: number | null;
  energy_millions: number | null;
  /** Sum of the CFDA-numbered dollars that landed in a bucket, in millions. */
  cfda_covered_millions: number | null;
  top_programs: FederalProgramShare[];
  fy: number | null;
  source: string;
  pending_reason?: string | null;
}

export interface FederalSpendingProvenance {
  source_name: string;
  source_url: string;
  api_endpoints: string[];
  fiscal_year: number | null;
  geography_basis: string;
  geography_caveat: string;
  program_bucket_basis: string;
  program_bucket_caveat: string;
  ingested_at: string;
  ingest_script: string;
  michigan_county_registry: string;
  michigan_county_registry_size: number;
  value_label: "VERIFIED" | "PENDING";
  populated: boolean;
  pending_reason: string | null;
  notes: string;
}

interface Payload {
  provenance: FederalSpendingProvenance;
  buckets: Array<{ field: string; label: string }>;
  counties: CountyFederalSpending[];
}

const payload = raw as unknown as Payload;

export const FEDERAL_SPENDING_PROVENANCE: FederalSpendingProvenance = payload.provenance;
export const FEDERAL_SPENDING_BUCKETS = payload.buckets;
export const FEDERAL_SPENDING_IS_POPULATED = true;

/** Every Michigan county with a published total, newest complete fiscal year. */
export const MICHIGAN_FEDERAL_SPENDING: CountyFederalSpending[] = payload.counties.filter(
  (c) => c.status === "populated" && c.total_awards_millions !== null,
);

/** All 83 records including pending ones, for provenance and audit views. */
export const FEDERAL_SPENDING_ALL_COUNTIES: readonly CountyFederalSpending[] = payload.counties;

export function getCountyFederalSpending(county: string): CountyFederalSpending | null {
  const key = county.replace(/\s+County$/i, "").trim().toLowerCase();
  return payload.counties.find((c) => c.county.toLowerCase() === key) ?? null;
}

/**
 * Share of a county's federal obligations that arrives as safety-net
 * assistance (Medicaid, food, housing, energy), 0-100, or null when the
 * inputs are missing. This is a ratio of published figures, not a model of
 * county revenue: the previous "federal dependency" score was an unsourced
 * illustrative table and has been removed.
 */
export function getSafetyNetShare(county: string): number | null {
  const rec = getCountyFederalSpending(county);
  if (!rec || rec.status !== "populated" || !rec.total_awards_millions) return null;
  const parts = [rec.medicaid_millions, rec.snap_millions, rec.housing_millions, rec.energy_millions];
  if (parts.every((p) => p === null)) return null;
  const sum = parts.reduce((s, p) => s + (p ?? 0), 0);
  return Math.round((sum / rec.total_awards_millions) * 1000) / 10;
}

/** Back-compat alias for the safety-net share. Returns null when unknown. */
export function n(county: string): number | null {
  return getSafetyNetShare(county);
}
