/**
 * Typed accessor for HUD CHAS county housing cost burden. The JSON payload
 * lives in hud-chas-county.generated.json so the fixture is diffable and
 * the vintage can be read at build time without touching this shim.
 * Regenerated by scripts/refresh-hud-chas-county.mjs; do not hand-edit.
 */
import raw from "./hud-chas-county.generated.json";

export interface ChasIncomeBandRecord {
  households: number;
  costBurdened30Pct: number | null;
  costBurdened50Pct: number | null;
}

export interface HudChasCountyRecord {
  countyFips: string;
  countyName: string;
  /** "populated" when HUD counts are present; "pending-ci" when the ingest
   * environment could not reach huduser.gov and CI must re-run. */
  status: "populated" | "pending-ci";
  /** T8_est1 - occupied housing units (universe), or null. */
  households: number | null;
  /** Households paying more than 30% of income on housing, or null. */
  costBurdened30Households: number | null;
  /** Households paying more than 50% of income on housing, or null. */
  costBurdened50Households: number | null;
  costBurdened30Pct: number | null;
  costBurdened50Pct: number | null;
  ownerCostBurdened30Pct: number | null;
  renterCostBurdened30Pct: number | null;
  byIncomeBand: Record<
    "le30ami" | "gt30le50ami" | "gt50le80ami" | "gt80le100ami" | "gt100ami",
    ChasIncomeBandRecord
  > | null;
  pendingReason: string | null;
}

export interface HudChasCountyProvenance {
  source_name: string;
  source_url: string;
  download_url: string | null;
  zip_sha256: string | null;
  table: string;
  vintage_window: string | null;
  candidate_vintages: string[];
  income_bands: string[];
  ingested_at: string;
  ingest_script: string;
  michigan_county_registry: string;
  michigan_county_registry_size: number;
  value_label: "VERIFIED" | "PENDING";
  populated: boolean;
  pending_reason: string | null;
  notes: string;
}

interface Payload {
  provenance: HudChasCountyProvenance;
  counties: HudChasCountyRecord[];
}

const payload = raw as Payload;

export const HUD_CHAS_COUNTY_PROVENANCE: HudChasCountyProvenance =
  payload.provenance;
export const HUD_CHAS_COUNTY_RECORDS: readonly HudChasCountyRecord[] =
  payload.counties;

const BY_FIPS = new Map<string, HudChasCountyRecord>(
  payload.counties.map((c) => [c.countyFips, c]),
);
const BY_NAME = new Map<string, HudChasCountyRecord>(
  payload.counties.map((c) => [c.countyName, c]),
);

export function getChasForCountyFips(fips: string): HudChasCountyRecord | null {
  return BY_FIPS.get(fips) ?? null;
}

export function getChasForCountyName(name: string): HudChasCountyRecord | null {
  return BY_NAME.get(name.replace(/\s+County$/i, "").trim()) ?? null;
}

/** True iff every county carries HUD counts. */
export const HUD_CHAS_IS_POPULATED = false;
