import type { LucideIcon } from "lucide-react";
import { HeartPulse, Home, Soup } from "lucide-react";

export type IntelligenceDomainSlug = "health" | "housing" | "food-security";

export interface IntelligenceDomain {
  name: string;
  icon: LucideIcon;
  slug: IntelligenceDomainSlug;
  updateFrequency: "Monthly" | "Quarterly" | "Annual";
  dataSource: string;
  metrics: readonly string[];
}

// Originally scaffolded with 10 domains (health, housing, food-security,
// energy, legal-aid, benefits, transportation, environment, public-safety,
// disability-access), most metrics generated by multiplying a real
// COUNTY_CROSS_DOMAIN field by an uncited "placeholder calibration ratio"
// and captioned with a specific but unsupported agency citation (e.g.
// "HUD / County Assessors", "MSP / FBI UCR"). 5 of those 10 domain slugs
// (benefits, transportation, environment, public-safety, disability-access)
// were never actually reachable as a Domain Dashboard view in the first
// place - their routes (/benefits, /transportation, /environment,
// /public-safety, /disability-access) point at unrelated, already-built,
// real pages, not this dashboard. Of the remaining 5 that did route here
// (health, housing, food-security, energy, legal-aid), energy and legal-aid
// had zero fields backed by real data for any county. This scaffold now
// covers only the 3 domains that route here AND have at least one field
// traceable to a real, ingested source - see FIXLOG.md.
export const INTELLIGENCE_DOMAINS = [
  {
    name: "Health",
    icon: HeartPulse,
    slug: "health",
    updateFrequency: "Annual",
    dataSource: "County Health Rankings 2025",
    metrics: ["uninsured_rate", "primary_care_access"],
  },
  {
    name: "Housing",
    icon: Home,
    slug: "housing",
    updateFrequency: "Annual",
    dataSource: "ACS 5-Year 2022",
    metrics: ["renter_burden_rate"],
  },
  {
    name: "Food Security",
    icon: Soup,
    slug: "food-security",
    updateFrequency: "Annual",
    dataSource: "County Health Rankings 2025 (Map the Meal Gap 2022, modeled)",
    metrics: ["food_insecurity_rate"],
  },
] as const satisfies readonly IntelligenceDomain[];

export const INTELLIGENCE_DOMAIN_MAP: Record<IntelligenceDomainSlug, IntelligenceDomain> = Object.fromEntries(
  INTELLIGENCE_DOMAINS.map((domain) => [domain.slug, domain]),
) as unknown as Record<IntelligenceDomainSlug, IntelligenceDomain>;

export function getIntelligenceDomain(slug: string | undefined): IntelligenceDomain {
  if (slug && slug in INTELLIGENCE_DOMAIN_MAP) {
    return INTELLIGENCE_DOMAIN_MAP[slug as IntelligenceDomainSlug];
  }

  return INTELLIGENCE_DOMAIN_MAP.health;
}

export function formatMetricName(metricKey: string) {
  return metricKey
    .split("_")
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join(" ");
}
