/**
 * Typed accessor for NCHS provisional county drug overdose death counts.
 * Payload in nchs-overdose-county.generated.json; regenerated by
 * scripts/refresh-nchs-overdose-county.mjs. Do not hand-edit.
 */
import raw from "./nchs-overdose-county.generated.json";

export interface OverdoseCountyRecord {
  countyFips: string;
  countyName: string;
  /** "suppressed" = NCHS withheld a count under 10 (null, never 0). */
  status: "populated" | "suppressed" | "pending-ci";
  /** 12-month-ending provisional count, or null. */
  provisionalDeaths12mo: number | null;
  pendingReason: string | null;
}

export interface OverdoseCountyProvenance {
  source_name: string;
  source_url: string;
  dataset_id: string;
  dataset_title: string | null;
  socrata_metadata_url: string;
  socrata_rows_updated_at: string | null;
  /** e.g. "2026-03" - the month the 12-month window ends. */
  period_ending: string | null;
  period_definition: string;
  resolved_fields: Record<string, string> | null;
  ingested_at: string;
  ingest_script: string;
  michigan_county_registry: string;
  michigan_county_registry_size: number;
  value_label: "VERIFIED" | "PENDING";
  populated: boolean;
  pending_reason: string | null;
  notes: string;
}

interface Payload {
  provenance: OverdoseCountyProvenance;
  counties: OverdoseCountyRecord[];
}

const payload = raw as Payload;

export const OVERDOSE_COUNTY_PROVENANCE: OverdoseCountyProvenance = payload.provenance;
export const OVERDOSE_COUNTY_RECORDS: readonly OverdoseCountyRecord[] = payload.counties;

const BY_FIPS = new Map<string, OverdoseCountyRecord>(payload.counties.map((c) => [c.countyFips, c]));
const BY_NAME = new Map<string, OverdoseCountyRecord>(payload.counties.map((c) => [c.countyName, c]));

export function getOverdoseForCountyFips(fips: string): OverdoseCountyRecord | null {
  return BY_FIPS.get(fips) ?? null;
}

export function getOverdoseForCountyName(name: string): OverdoseCountyRecord | null {
  return BY_NAME.get(name.replace(/\s+County$/i, "").trim()) ?? null;
}

/** Human-readable period, e.g. "12 months ending Mar 2026", or null. */
export function overdosePeriodLabel(): string | null {
  const p = OVERDOSE_COUNTY_PROVENANCE.period_ending;
  if (!p) return null;
  const [y, m] = p.split("-").map(Number);
  const month = new Date(Date.UTC(y, m - 1, 1)).toLocaleString("en-US", { month: "short", timeZone: "UTC" });
  return `12 months ending ${month} ${y}`;
}

export const OVERDOSE_IS_POPULATED = false;
