/**
 * Typed accessor for Census SAIPE county poverty and median household
 * income. Payload in saipe-county.generated.json; regenerated by
 * scripts/refresh-saipe-county.mjs. Do not hand-edit.
 */
import raw from "./saipe-county.generated.json";

export type SaipeMeasureId =
  | "povertyPct"
  | "childPovertyPct"
  | "schoolAgePovertyPct"
  | "medianHouseholdIncome";

export interface SaipeMeasure {
  id: SaipeMeasureId;
  label: string;
  unit: "percent" | "dollars";
  value_label: "VERIFIED";
}

export interface SaipeCountyRecord {
  countyFips: string;
  countyName: string;
  status: "populated" | "pending-ci";
  values: Record<SaipeMeasureId, number | null>;
  /** Census 90% confidence bounds [lower, upper] where published. */
  confidence: Record<"povertyPct" | "childPovertyPct" | "medianHouseholdIncome", (number | null)[]>;
  peopleInPoverty: number | null;
  childrenInPoverty: number | null;
  pendingReason: string | null;
}

export interface SaipeProvenance {
  source_name: string;
  source_url: string;
  download_url: string | null;
  estimate_year: number | null;
  ingested_at: string;
  ingest_script: string;
  michigan_county_registry: string;
  michigan_county_registry_size: number;
  statewide: Record<string, number | null> | null;
  value_label: "VERIFIED" | "PENDING";
  populated: boolean;
  pending_reason: string | null;
  notes: string;
}

interface Payload {
  provenance: SaipeProvenance;
  measures: SaipeMeasure[];
  counties: SaipeCountyRecord[];
}

const payload = raw as Payload;

export const SAIPE_PROVENANCE: SaipeProvenance = payload.provenance;
export const SAIPE_MEASURES: readonly SaipeMeasure[] = payload.measures;
export const SAIPE_COUNTY_RECORDS: readonly SaipeCountyRecord[] = payload.counties;

const BY_FIPS = new Map<string, SaipeCountyRecord>(payload.counties.map((c) => [c.countyFips, c]));
const BY_NAME = new Map<string, SaipeCountyRecord>(payload.counties.map((c) => [c.countyName, c]));

export function getSaipeForCountyFips(fips: string): SaipeCountyRecord | null {
  return BY_FIPS.get(fips) ?? null;
}

export function getSaipeForCountyName(name: string): SaipeCountyRecord | null {
  return BY_NAME.get(name.replace(/\s+County$/i, "").trim()) ?? null;
}

/** One measure for one county, or null while pending or unpublished. */
export function getSaipeValue(countyName: string, measureId: SaipeMeasureId): number | null {
  const rec = getSaipeForCountyName(countyName);
  if (!rec || rec.status !== "populated") return null;
  return rec.values[measureId] ?? null;
}

/** Michigan statewide figures from the same release, for benchmarking. */
export const SAIPE_STATEWIDE = payload.provenance.statewide;

/** Vintage label for point-of-use citation, e.g. "SAIPE 2024". */
export function saipeVintageLabel(): string {
  return payload.provenance.estimate_year ? `SAIPE ${payload.provenance.estimate_year}` : "pending first pull";
}

export const SAIPE_IS_POPULATED = true;
