// SNAP Michigan data.
//
// County-level enrollment lives in the companion JSON file
// `snapCountyGenerated.json` and is regenerated by
// `node scripts/build-snap-county-dataset.mjs` from the USDA FNS-388A
// project-area / county participation release. The seed values were
// transcribed from the published FY2022 county tables (most recent county
// file, ~2-year lag); the script overwrites them in place once a newer
// FNS-388A release parses and validates. Do not hand-edit the JSON.
//   Source: USDA FNS "SNAP: Average Monthly Participation by State and County"
//   URL: https://www.fns.usda.gov/pd/supplemental-nutrition-assistance-program-snap
//   Figures are average monthly participants / certified households for the fiscal year.
//
// State-level enrollment and benefit issuance are not part of the county
// (388A) release, so they stay defined here:
//   Source: USDA FNS State Data Tables (snap-persons-6.xlsx, snap-households-6.xlsx
//     on fna.usda.gov, "Data as of June 12, 2026", February 2026 Preliminary column -
//     newest common month with US National for which the file's TOTAL row is a
//     clean integer, i.e. no imputation)
//   URL: https://www.fns.usda.gov/pd/supplemental-nutrition-assistance-program-snap
//   Preliminary: yes. USDA flags February 2026 figures as preliminary and
//     subject to significant revision.
// Retailer counts: USDA SNAP Retailer Locator, December 31, 2025
//   County-level retailer counts not available pending CSV parse - marked null.
//   Statewide total (9,200+) is from V3_SOURCE_AUDIT.md.
// MDHHS Green Book extractor (specced in V3_DESIGN.md) would reduce county lag to ~6 weeks.
// Do not add fabricated estimates. Missing data is null.
import snapCountyData from "./snapCountyGenerated.json";

export interface SnapCountyData {
  county: string; // matches michigan-county-profiles keys (no " County" suffix)
  fips: string; // 5-digit FIPS, e.g. "26163" for Wayne
  enrollmentTotal: number | null; // FY2022 avg monthly participants
  enrollmentHouseholds: number | null; // FY2022 avg monthly certified households
  enrollmentAsOf: string; // "FY2022"
  sourceName: string;
  sourceUrl: string;
  retailerCount: number | null; // from USDA SNAP Retailer Locator; null until CSV parsed
  retailerAsOf: string | null; // "December 2025" or null
  retailerSourceUrl: string | null;
}

export interface SnapCountyProvenance {
  dataset: string;
  vintage: string;
  source_name: string;
  source_url: string;
  release_zip: string;
  fetched_at: string;
  transform_script: string;
  counties_total: number;
  note: string;
}

export interface SnapStateData {
  stateTotal: number; // persons participating, most recent published month
  stateAsOf: string; // e.g. "February 2026 (Preliminary)"
  stateHouseholds: number; // households participating, same month as stateTotal
  stateHouseholdsAsOf: string; // same vintage string as stateAsOf
  stateSourceUrl: string;
  benefitIssuanceMonthly: number; // state-level monthly benefit dollars
  benefitAsOf: string;
  benefitSourceUrl: string;
}

const FNS_SOURCE_URL =
  "https://www.fns.usda.gov/pd/supplemental-nutrition-assistance-program-snap";

const countyPayload = snapCountyData as {
  provenance: SnapCountyProvenance;
  counties: SnapCountyData[];
};

// All 83 Michigan counties - USDA FNS FY2022 average monthly participation.
// Regenerated by scripts/build-snap-county-dataset.mjs; do not hand-edit.
export const SNAP_COUNTY_FALLBACK: SnapCountyData[] = countyPayload.counties;

export const SNAP_COUNTY_PROVENANCE: SnapCountyProvenance =
  countyPayload.provenance;

export const SNAP_STATE_FALLBACK: SnapStateData = {
  // Michigan statewide monthly enrollment - USDA FNS state tables.
  // Read from snap-persons-6.xlsx (row "Michigan", column "February 2026 Preliminary")
  // and snap-households-6.xlsx (same row/column), both "Data as of June 12, 2026".
  // Preliminary flag: the file's own footer marks February 2026 figures as
  // "preliminary and subject to significant revision".
  stateTotal: 1_400_731,
  stateAsOf: "February 2026 (Preliminary)",
  stateHouseholds: 743_752,
  stateHouseholdsAsOf: "February 2026 (Preliminary)",
  stateSourceUrl: FNS_SOURCE_URL,
  // Monthly issuance: Michigan FY2025 monthly average benefit issuance
  // USDA FNS state issuance tables - most current available
  benefitIssuanceMonthly: 280_000_000,
  benefitAsOf: "January 2026",
  benefitSourceUrl: FNS_SOURCE_URL,
};
