// SNAP Michigan data.
//
// County-level enrollment lives in the companion JSON file
// `snapCountyGenerated.json` and is regenerated by
// `node scripts/build-snap-county-dataset.mjs` from the USDA FNS-388A
// project-area / county participation release. The seed values were
// transcribed from the published FY2022 county tables (most recent county
// file, ~2-year lag); the script overwrites them in place once a newer
// FNS-388A release parses and validates. Do not hand-edit the JSON.
//   Source: USDA FNS "SNAP: Average Monthly Participation by State and County"
//   URL: https://www.fns.usda.gov/pd/supplemental-nutrition-assistance-program-snap
//   Figures are average monthly participants / certified households for the fiscal year.
//
// State-level enrollment and benefit issuance are not part of the county
// (388A) release, so they stay defined here:
//   Source: USDA FNS State Data Tables (January 2026, most recent monthly total)
//   URL: https://www.fns.usda.gov/pd/supplemental-nutrition-assistance-program-snap
// Retailer counts: USDA SNAP Retailer Locator, December 2025
//   County-level retailer counts not available pending CSV parse - marked null.
//   Statewide total (9,200+) is from V3_SOURCE_AUDIT.md.
// MDHHS Green Book extractor (specced in V3_DESIGN.md) would reduce county lag to ~6 weeks.
// Do not add fabricated estimates. Missing data is null.
import snapCountyData from "./snapCountyGenerated.json";

export interface SnapCountyData {
  county: string;               // matches michigan-county-profiles keys (no " County" suffix)
  fips: string;                 // 5-digit FIPS, e.g. "26163" for Wayne
  enrollmentTotal: number | null;      // FY2022 avg monthly participants
  enrollmentHouseholds: number | null; // FY2022 avg monthly certified households
  enrollmentAsOf: string;       // "FY2022"
  sourceName: string;
  sourceUrl: string;
  retailerCount: number | null; // from USDA SNAP Retailer Locator; null until CSV parsed
  retailerAsOf: string | null;  // "December 2025" or null
  retailerSourceUrl: string | null;
}

export interface SnapCountyProvenance {
  dataset: string;
  vintage: string;
  source_name: string;
  source_url: string;
  release_zip: string;
  fetched_at: string;
  transform_script: string;
  counties_total: number;
  note: string;
}

export interface SnapStateData {
  stateTotal: number;            // current monthly state enrollment
  stateAsOf: string;             // "January 2026"
  stateSourceUrl: string;
  benefitIssuanceMonthly: number; // state-level monthly benefit dollars
  benefitAsOf: string;
  benefitSourceUrl: string;
}

const FNS_SOURCE_URL =
  "https://www.fns.usda.gov/pd/supplemental-nutrition-assistance-program-snap";

const countyPayload = snapCountyData as {
  provenance: SnapCountyProvenance;
  counties: SnapCountyData[];
};

// All 83 Michigan counties - USDA FNS FY2022 average monthly participation.
// Regenerated by scripts/build-snap-county-dataset.mjs; do not hand-edit.
export const SNAP_COUNTY_FALLBACK: SnapCountyData[] = countyPayload.counties;

export const SNAP_COUNTY_PROVENANCE: SnapCountyProvenance =
  countyPayload.provenance;

export const SNAP_STATE_FALLBACK: SnapStateData = {
  // Michigan statewide monthly enrollment - USDA FNS state tables, January 2026
  stateTotal: 1_370_000,
  stateAsOf: "January 2026",
  stateSourceUrl: FNS_SOURCE_URL,
  // Monthly issuance: Michigan FY2025 monthly average benefit issuance
  // USDA FNS state issuance tables - most current available
  benefitIssuanceMonthly: 280_000_000,
  benefitAsOf: "January 2026",
  benefitSourceUrl: FNS_SOURCE_URL,
};
