import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const PRIORITY_ROUTES = [
  '/',
  '/opportunity',
  '/find-care',
  '/zip/48201',
  '/compare',
  '/health-map',
  '/tax-comparison',
  '/health-equity-atlas',
  '/data-sources',
  '/methodology',
  '/about',
  '/data',
  '/data-explorer',
  '/explore',
  '/disaster-history',
  '/equity',
  '/energy-burden',
  '/domain-dashboard',
  '/detection-gap',
  '/public-investment',
  '/officials',
  '/transparency',
];

type ViolationRow = {
  route: string;
  id: string;
  impact: string;
  description: string;
  nodes: number;
  help: string;
};

const allViolations: ViolationRow[] = [];

test.describe('A11y audit - priority routes', () => {
  test.beforeEach(async ({ page }) => {
    // Suppress first-visit onboarding tour so axe doesn't sample the
    // card mid-fade (transparent card reveals crisis-bar coral and
    // produces false-positive contrast violations).
    await page.addInitScript(() => {
      localStorage.setItem('accessmi_tour_seen', 'true');
    });
  });

  for (const route of PRIORITY_ROUTES) {
    test(`axe scan ${route}`, async ({ page }) => {
      await page.goto(route, { waitUntil: 'domcontentloaded' });
      await page.waitForLoadState('networkidle').catch(() => {});

      const results = await new AxeBuilder({ page })
        .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
        .analyze();

      for (const v of results.violations) {
        allViolations.push({
          route,
          id: v.id,
          impact: v.impact ?? 'unknown',
          description: v.description,
          nodes: v.nodes.length,
          help: v.helpUrl,
        });
      }

      const criticalOrSerious = results.violations.filter(
        (v) => v.impact === 'critical' || v.impact === 'serious'
      );
      console.log(
        `[a11y] ${route}: ${criticalOrSerious.length} critical/serious, ${results.violations.length - criticalOrSerious.length} other`
      );

      // Hard gate. Keep individual route tests independent: using Playwright's
      // serial mode caused every later route to be skipped after one failure,
      // hiding the actual breadth of regressions and wasting a CI cycle.
      expect(
        criticalOrSerious.map((v) => `${v.impact}:${v.id} x${v.nodes.length}`),
        `critical/serious a11y violations on ${route}`
      ).toEqual([]);
    });
  }

  test.afterAll(() => {
    const lines = [
      '# Accessibility Violations',
      '',
      `Generated by a11y-priority-routes.spec.ts at ${new Date().toISOString()}`,
      `Total rule-level violations across priority routes: ${allViolations.length}`,
      '',
    ];
    if (allViolations.length === 0) {
      lines.push(
        '**Status: clean.** No WCAG 2.0/2.1 A/AA violations detected across the priority routes:',
        '',
        ...PRIORITY_ROUTES.map((r) => `- ${r}`),
      );
    } else {
      lines.push(
        '| Route | Rule | Impact | Nodes | Description |',
        '| --- | --- | --- | --- | --- |',
        ...allViolations.map(
          (v) =>
            `| ${v.route} | [${v.id}](${v.help}) | ${v.impact} | ${v.nodes} | ${v.description.replace(/\|/g, '\\|')} |`
        ),
      );
    }
    const target = join(__dirname, '../../../A11Y_VIOLATIONS.md');
    try {
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, lines.join('\n'), 'utf8');
    } catch {
      // best-effort
    }
  });
});
