import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { ClipboardList, GraduationCap, Printer } from "lucide-react";

const CLINIC_ITEMS = [
  { id: "insurance", label: "Insurance card (or Medicaid ID)" },
  { id: "photo-id", label: "Photo ID" },
  { id: "meds-list", label: "List of current medications and dosages" },
  { id: "questions", label: "Written questions for your provider" },
  { id: "records", label: "Recent lab results or medical records (if available)" },
  { id: "transport", label: "Transportation plan confirmed (ride, bus, etc.)" },
  { id: "copay", label: "Co-pay or payment method" },
  { id: "support", label: "Support person arranged (if needed)" },
];

const SCHOOL_ITEMS = [
  { id: "pickup", label: "Pickup and drop-off plan confirmed" },
  { id: "emergency", label: "Emergency contacts updated with school" },
  { id: "meds-school", label: "Medications at school (inhaler, EpiPen, etc.) verified" },
  { id: "afterschool", label: "After-school caregiver arrangement confirmed" },
  { id: "bus-route", label: "Bus route and stop location reviewed" },
  { id: "lunch", label: "Lunch plan set (packed or school meal)" },
  { id: "contact-card", label: "Child has emergency contact card in backpack" },
];

interface VisitPrepChecklistProps {
  trigger?: React.ReactNode;
}

const VisitPrepChecklist = ({ trigger }: VisitPrepChecklistProps) => {
  const [clinicChecked, setClinicChecked] = useState<Set<string>>(new Set());
  const [schoolChecked, setSchoolChecked] = useState<Set<string>>(new Set());

  const toggle = (set: Set<string>, setFn: React.Dispatch<React.SetStateAction<Set<string>>>, id: string) => {
    const next = new Set(set);
    next.has(id) ? next.delete(id) : next.add(id);
    setFn(next);
  };

  const handlePrint = (tab: "clinic" | "school") => {
    const items = tab === "clinic" ? CLINIC_ITEMS : SCHOOL_ITEMS;
    const checked = tab === "clinic" ? clinicChecked : schoolChecked;
    const title = tab === "clinic" ? "Clinic Visit Prep Checklist" : "Child School-Day Prep Checklist";
    const content = items
      .map((item) => `${checked.has(item.id) ? "☑" : "☐"} ${item.label}`)
      .join("\n");
    const printContent = `${title}\n${"=".repeat(40)}\n\n${content}\n\nGenerated by Access Michigan — accessmi.org\nNo personal information is stored.`;

    const blob = new Blob([printContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${tab}-checklist.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Dialog>
      <DialogTrigger asChild>
        {trigger || (
          <Button variant="outline" size="sm">
            <ClipboardList className="h-4 w-4" />
            Visit Prep Checklist
          </Button>
        )}
      </DialogTrigger>
      <DialogContent className="max-w-lg max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <ClipboardList className="h-5 w-5 text-primary" />
            Visit Prep Checklist
          </DialogTitle>
          <p className="text-sm text-muted-foreground">
            Prepare for your visit. Check items as you go. Download when ready.
          </p>
        </DialogHeader>

        <Tabs defaultValue="clinic">
          <TabsList className="w-full">
            <TabsTrigger value="clinic" className="flex-1">
              <ClipboardList className="h-3.5 w-3.5 mr-1.5" />
              Clinic Visit
            </TabsTrigger>
            <TabsTrigger value="school" className="flex-1">
              <GraduationCap className="h-3.5 w-3.5 mr-1.5" />
              School Day
            </TabsTrigger>
          </TabsList>

          <TabsContent value="clinic" className="space-y-4 mt-4">
            <div className="space-y-3">
              {CLINIC_ITEMS.map((item) => (
                <div key={item.id} className="flex items-start gap-3">
                  <Checkbox
                    id={`clinic-${item.id}`}
                    checked={clinicChecked.has(item.id)}
                    onCheckedChange={() => toggle(clinicChecked, setClinicChecked, item.id)}
                  />
                  <label
                    htmlFor={`clinic-${item.id}`}
                    className={`text-sm cursor-pointer ${clinicChecked.has(item.id) ? "line-through text-muted-foreground" : "text-foreground"}`}
                  >
                    {item.label}
                  </label>
                </div>
              ))}
            </div>
            <div className="flex items-center justify-between pt-2">
              <Badge variant="outline" className="text-xs">
                {clinicChecked.size}/{CLINIC_ITEMS.length} complete
              </Badge>
              <Button variant="outline" size="sm" onClick={() => handlePrint("clinic")}>
                <Printer className="h-3.5 w-3.5" />
                Download Checklist
              </Button>
            </div>
          </TabsContent>

          <TabsContent value="school" className="space-y-4 mt-4">
            <div className="space-y-3">
              {SCHOOL_ITEMS.map((item) => (
                <div key={item.id} className="flex items-start gap-3">
                  <Checkbox
                    id={`school-${item.id}`}
                    checked={schoolChecked.has(item.id)}
                    onCheckedChange={() => toggle(schoolChecked, setSchoolChecked, item.id)}
                  />
                  <label
                    htmlFor={`school-${item.id}`}
                    className={`text-sm cursor-pointer ${schoolChecked.has(item.id) ? "line-through text-muted-foreground" : "text-foreground"}`}
                  >
                    {item.label}
                  </label>
                </div>
              ))}
            </div>
            <div className="flex items-center justify-between pt-2">
              <Badge variant="outline" className="text-xs">
                {schoolChecked.size}/{SCHOOL_ITEMS.length} complete
              </Badge>
              <Button variant="outline" size="sm" onClick={() => handlePrint("school")}>
                <Printer className="h-3.5 w-3.5" />
                Download Checklist
              </Button>
            </div>
          </TabsContent>
        </Tabs>

        <p className="text-xs text-muted-foreground text-center mt-2">
          No personal information is stored. This checklist stays on your device.
        </p>
      </DialogContent>
    </Dialog>
  );
};

export default VisitPrepChecklist;
